INSERT INTO hero VALUES (652, 'Superboy-Prime', 'Male', 'blue', 'Kryptonian', 'Black / Blue', 180, 'DC Comics', '-', 'bad', 77);
INSERT INTO hero VALUES (653, 'Supergirl', 'Female', 'blue', 'Kryptonian', 'Blond', 165, 'DC Comics', '-', 'good', 54);
INSERT INTO hero VALUES (654, 'Superman', 'Male', 'blue', 'Kryptonian', 'Black', 191, 'DC Comics', '-', 'good', 101);
INSERT INTO hero VALUES (655, 'Swamp Thing', 'Male', 'red', 'God / Eternal', 'No Hair', -99, 'DC Comics', 'green', 'bad', -99);
INSERT INTO hero VALUES (656, 'Swarm', 'Male', 'yellow', 'Mutant', 'No Hair', 196, 'Marvel Comics', 'yellow', 'bad', 47);
INSERT INTO hero VALUES (657, 'Sylar', 'Male', '-', '-', '-', -99, 'NBC - Heroes', '-', 'bad', -99);
INSERT INTO hero VALUES (658, 'Synch', 'Male', 'brown', '-', 'Black', 180, 'Marvel Comics', '-', 'good', 74);
INSERT INTO hero VALUES (659, 'T-1000', 'Male', '-', 'Android', '-', 183, 'Dark Horse Comics', 'silver', 'bad', 146);
INSERT INTO hero VALUES (660, 'T-800', 'Male', 'red', 'Cyborg', '-', -99, 'Dark Horse Comics', '-', 'bad', 176);
INSERT INTO hero VALUES (661, 'T-850', 'Male', 'red', 'Cyborg', '-', -99, 'Dark Horse Comics', '-', 'bad', 198);
INSERT INTO hero VALUES (662, 'T-X', 'Female', '-', 'Cyborg', '-', -99, 'Dark Horse Comics', 'silver', 'bad', 149);
INSERT INTO hero VALUES (663, 'Taskmaster', 'Male', 'brown', 'Human', 'Brown', 188, 'Marvel Comics', '-', 'bad', 99);
INSERT INTO hero VALUES (664, 'Tempest', 'Female', 'brown', '-', 'Black', 163, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (665, 'Thanos', 'Male', 'red', 'Eternal', 'No Hair', 201, 'Marvel Comics', 'purple', 'bad', 443);
INSERT INTO hero VALUES (666, 'The Cape', 'Male', '-', '-', '-', -99, NULL, '-', 'good', -99);
INSERT INTO hero VALUES (667, 'The Comedian', 'Male', 'brown', 'Human', 'Black', 188, 'DC Comics', '-', 'neutral', 101);
INSERT INTO hero VALUES (668, 'Thing', 'Male', 'blue', 'Human / Radiation', 'No Hair', 183, 'Marvel Comics', '-', 'good', 225);
INSERT INTO hero VALUES (669, 'Thor', 'Male', 'blue', 'Asgardian', 'Blond', 198, 'Marvel Comics', '-', 'good', 288);
INSERT INTO hero VALUES (670, 'Thor Girl', 'Female', 'blue', 'Asgardian', 'Blond', 175, 'Marvel Comics', '-', 'good', 143);
INSERT INTO hero VALUES (671, 'Thunderbird', 'Male', 'brown', '-', 'Black', 185, 'Marvel Comics', '-', 'good', 101);
INSERT INTO hero VALUES (672, 'Thunderbird II', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (673, 'Thunderbird III', 'Male', 'brown', '-', 'Black', 175, 'Marvel Comics', '-', 'good', 74);
INSERT INTO hero VALUES (674, 'Thunderstrike', 'Male', 'blue', '-', 'Blond', 198, 'Marvel Comics', '-', 'good', 288);
INSERT INTO hero VALUES (675, 'Thundra', 'Female', 'green', '-', 'Red', 218, 'Marvel Comics', '-', 'good', 158);
INSERT INTO hero VALUES (676, 'Tiger Shark', 'Male', 'grey', 'Human', 'No Hair', 185, 'Marvel Comics', 'grey', 'bad', 203);
INSERT INTO hero VALUES (677, 'Tigra', 'Female', 'green', '-', 'Auburn', 178, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (678, 'Tinkerer', 'Male', 'brown', '-', 'White', 163, 'Marvel Comics', '-', 'bad', 54);
INSERT INTO hero VALUES (679, 'Titan', 'Male', '-', '-', '-', -99, 'HarperCollins', '-', 'good', -99);
INSERT INTO hero VALUES (680, 'Toad', 'Male', 'black', 'Mutant', 'Brown', 175, 'Marvel Comics', 'green', 'neutral', 76);
INSERT INTO hero VALUES (681, 'Toxin', 'Male', 'blue', 'Symbiote', 'Brown', 188, 'Marvel Comics', '-', 'good', 97);
INSERT INTO hero VALUES (682, 'Toxin', 'Male', 'black', 'Symbiote', 'Blond', 191, 'Marvel Comics', '-', 'good', 117);
INSERT INTO hero VALUES (683, 'Tracy Strauss', 'Female', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (684, 'Trickster', 'Male', 'blue', 'Human', 'Blond', 183, 'DC Comics', '-', '-', 81);
INSERT INTO hero VALUES (685, 'Trigon', 'Male', 'yellow', 'God / Eternal', 'Black', -99, 'DC Comics', 'red', 'bad', -99);
INSERT INTO hero VALUES (686, 'Triplicate Girl', 'Female', 'purple', '-', 'Brown', 168, 'DC Comics', '-', 'good', 59);
INSERT INTO hero VALUES (687, 'Triton', 'Male', 'green', 'Inhuman', 'No Hair', 188, 'Marvel Comics', 'green', 'good', 86);
INSERT INTO hero VALUES (688, 'Two-Face', 'Male', '-', '-', '-', 183, 'DC Comics', '-', 'bad', 82);
INSERT INTO hero VALUES (689, 'Ultragirl', 'Female', 'blue', '-', 'Blond', 168, 'Marvel Comics', '-', 'good', 105);
INSERT INTO hero VALUES (690, 'Ultron', 'Male', 'red', 'Android', '-', 206, 'Marvel Comics', 'silver', 'bad', 331);
INSERT INTO hero VALUES (691, 'Utgard-Loki', 'Male', 'blue', 'Frost Giant', 'White', 15.2, 'Marvel Comics', '-', 'bad', 58);
INSERT INTO hero VALUES (692, 'Vagabond', 'Female', 'blue', '-', 'Strawberry Blond', 168, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (693, 'Valerie Hart', 'Female', 'hazel', '-', 'Black', 175, 'Team Epic TV', '-', 'good', 56);
INSERT INTO hero VALUES (694, 'Valkyrie', 'Female', 'blue', '-', 'Blond', 191, 'Marvel Comics', '-', 'good', 214);
INSERT INTO hero VALUES (695, 'Vanisher', 'Male', 'green', '-', 'No Hair', 165, 'Marvel Comics', '-', 'bad', 79);
INSERT INTO hero VALUES (696, 'Vegeta', 'Male', '-', 'Saiyan', 'Black', 168, 'Shueisha', '-', 'bad', 73);
INSERT INTO hero VALUES (697, 'Venom', 'Male', 'blue', 'Symbiote', 'Strawberry Blond', 191, 'Marvel Comics', '-', 'bad', 117);
INSERT INTO hero VALUES (698, 'Venom II', 'Male', 'brown', '-', 'Black', 175, 'Marvel Comics', '-', 'bad', 50);
INSERT INTO hero VALUES (699, 'Venom III', 'Male', 'brown', 'Symbiote', 'Brown', 229, 'Marvel Comics', '-', 'bad', 334);
INSERT INTO hero VALUES (700, 'Venompool', 'Male', '-', 'Symbiote', '-', 226, 'Marvel Comics', '-', '-', -99);
INSERT INTO hero VALUES (701, 'Vertigo II', 'Female', 'blue', '-', 'Silver', 168, 'Marvel Comics', '-', 'good', 52);
INSERT INTO hero VALUES (702, 'Vibe', 'Male', 'brown', 'Human', 'Black', 178, 'DC Comics', '-', 'good', 71);
INSERT INTO hero VALUES (703, 'Vindicator', 'Female', 'green', 'Human', 'Red', 165, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (704, 'Vindicator', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (705, 'Violator', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (706, 'Violet Parr', 'Female', 'violet', 'Human', 'Black', 137, 'Dark Horse Comics', '-', 'good', 41);
INSERT INTO hero VALUES (707, 'Vision', 'Male', 'gold', 'Android', 'No Hair', 191, 'Marvel Comics', 'red', 'good', 135);
INSERT INTO hero VALUES (708, 'Vision II', '-', 'red', '-', 'No Hair', 191, 'Marvel Comics', '-', 'good', 135);
INSERT INTO hero VALUES (709, 'Vixen', 'Female', 'amber', 'Human', 'Black', 175, 'DC Comics', '-', 'good', 63);
INSERT INTO hero VALUES (710, 'Vulcan', 'Male', 'black', '-', 'Black', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (711, 'Vulture', 'Male', 'brown', 'Human', 'No Hair', 180, 'Marvel Comics', '-', 'bad', 79);
INSERT INTO hero VALUES (712, 'Walrus', 'Male', 'blue', 'Human', 'Black', 183, 'Marvel Comics', '-', 'bad', 162);
INSERT INTO hero VALUES (713, 'War Machine', 'Male', 'brown', 'Human', 'Brown', 185, 'Marvel Comics', '-', 'good', 95);
INSERT INTO hero VALUES (714, 'Warbird', 'Female', 'blue', '-', 'Blond', 180, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (715, 'Warlock', 'Male', 'red', '-', 'Blond', 188, 'Marvel Comics', '-', 'good', 108);
INSERT INTO hero VALUES (716, 'Warp', 'Male', 'brown', '-', 'Black', 173, 'DC Comics', '-', 'bad', 67);
INSERT INTO hero VALUES (717, 'Warpath', 'Male', 'brown', 'Mutant', 'Black', 218, 'Marvel Comics', '-', 'good', 158);
INSERT INTO hero VALUES (718, 'Wasp', 'Female', 'blue', 'Human', 'Auburn', 163, 'Marvel Comics', '-', 'good', 50);
INSERT INTO hero VALUES (719, 'Watcher', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (720, 'Weapon XI', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (721, 'White Canary', 'Female', 'brown', 'Human', 'Black', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (722, 'White Queen', 'Female', 'blue', '-', 'Blond', 178, 'Marvel Comics', '-', 'good', 65);
INSERT INTO hero VALUES (723, 'Wildfire', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (724, 'Winter Soldier', 'Male', 'brown', 'Human', 'Brown', 175, 'Marvel Comics', '-', 'good', 117);
INSERT INTO hero VALUES (725, 'Wiz Kid', '-', 'brown', '-', 'Black', 140, 'Marvel Comics', '-', 'good', 39);
INSERT INTO hero VALUES (726, 'Wolfsbane', 'Female', 'green', '-', 'Auburn', 366, 'Marvel Comics', '-', 'good', 473);
INSERT INTO hero VALUES (727, 'Wolverine', 'Male', 'blue', 'Mutant', 'Black', 160, 'Marvel Comics', '-', 'good', 135);
INSERT INTO hero VALUES (728, 'Wonder Girl', 'Female', 'blue', 'Demi-God', 'Blond', 165, 'DC Comics', '-', 'good', 51);
INSERT INTO hero VALUES (729, 'Wonder Man', 'Male', 'red', '-', 'Black', 188, 'Marvel Comics', '-', 'good', 171);
INSERT INTO hero VALUES (730, 'Wonder Woman', 'Female', 'blue', 'Amazon', 'Black', 183, 'DC Comics', '-', 'good', 74);
INSERT INTO hero VALUES (731, 'Wondra', 'Female', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (732, 'Wyatt Wingfoot', 'Male', 'brown', '-', 'Black', 196, 'Marvel Comics', '-', 'good', 117);
INSERT INTO hero VALUES (733, 'X-23', 'Female', 'green', 'Mutant / Clone', 'Black', 155, 'Marvel Comics', '-', 'good', 50);
INSERT INTO hero VALUES (734, 'X-Man', 'Male', 'blue', '-', 'Brown', 175, 'Marvel Comics', '-', 'good', 61);
INSERT INTO hero VALUES (735, 'Yellow Claw', 'Male', 'blue', '-', 'No Hair', 188, 'Marvel Comics', '-', 'bad', 95);
INSERT INTO hero VALUES (736, 'Yellowjacket', 'Male', 'blue', 'Human', 'Blond', 183, 'Marvel Comics', '-', 'good', 83);
INSERT INTO hero VALUES (737, 'Yellowjacket II', 'Female', 'blue', 'Human', 'Strawberry Blond', 165, 'Marvel Comics', '-', 'good', 52);
INSERT INTO hero VALUES (738, 'Ymir', 'Male', 'white', 'Frost Giant', 'No Hair', 304.8, 'Marvel Comics', 'white', 'good', -99);
INSERT INTO hero VALUES (739, 'Yoda', 'Male', 'brown', 'Yoda''s species', 'White', 66, 'George Lucas', 'green', 'good', 17);
INSERT INTO hero VALUES (740, 'Zatanna', 'Female', 'blue', 'Human', 'Black', 170, 'DC Comics', '-', 'good', 57);
INSERT INTO hero VALUES (741, 'Zoom', 'Male', 'red', '-', 'Brown', 185, 'DC Comics', '-', 'bad', 81);
INSERT INTO hero VALUES (8, 'A-Bomb', 'Male', 'yellow', 'Human', 'No Hair', 203, 'Marvel Comics', '-', 'good', 441);
INSERT INTO hero VALUES (9, 'Abe Sapien', 'Male', 'blue', 'Icthyo Sapien', 'No Hair', 191, 'Dark Horse Comics', 'blue', 'good', 65);
INSERT INTO hero VALUES (10, 'Abin Sur', 'Male', 'blue', 'Ungaran', 'No Hair', 185, 'DC Comics', 'red', 'good', 90);
INSERT INTO hero VALUES (11, 'Abomination', 'Male', 'green', 'Human / Radiation', 'No Hair', 203, 'Marvel Comics', '-', 'bad', 441);
INSERT INTO hero VALUES (12, 'Abraxas', 'Male', 'blue', 'Cosmic Entity', 'Black', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (13, 'Absorbing Man', 'Male', 'blue', 'Human', 'No Hair', 193, 'Marvel Comics', '-', 'bad', 122);
INSERT INTO hero VALUES (14, 'Adam Monroe', 'Male', 'blue', '-', 'Blond', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (15, 'Adam Strange', 'Male', 'blue', 'Human', 'Blond', 185, 'DC Comics', '-', 'good', 88);
INSERT INTO hero VALUES (16, 'Agent 13', 'Female', 'blue', '-', 'Blond', 173, 'Marvel Comics', '-', 'good', 61);
INSERT INTO hero VALUES (17, 'Agent Bob', 'Male', 'brown', 'Human', 'Brown', 178, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (18, 'Agent Zero', 'Male', '-', '-', '-', 191, 'Marvel Comics', '-', 'good', 104);
INSERT INTO hero VALUES (19, 'Air-Walker', 'Male', 'blue', '-', 'White', 188, 'Marvel Comics', '-', 'bad', 108);
INSERT INTO hero VALUES (20, 'Ajax', 'Male', 'brown', 'Cyborg', 'Black', 193, 'Marvel Comics', '-', 'bad', 90);
INSERT INTO hero VALUES (21, 'Alan Scott', 'Male', 'blue', '-', 'Blond', 180, 'DC Comics', '-', 'good', 90);
INSERT INTO hero VALUES (22, 'Alex Mercer', 'Male', '-', 'Human', '-', -99, 'Wildstorm', '-', 'bad', -99);
INSERT INTO hero VALUES (23, 'Alex Woolsly', 'Male', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (24, 'Alfred Pennyworth', 'Male', 'blue', 'Human', 'Black', 178, 'DC Comics', '-', 'good', 72);
INSERT INTO hero VALUES (25, 'Alien', 'Male', '-', 'Xenomorph XX121', 'No Hair', 244, 'Dark Horse Comics', 'black', 'bad', 169);
INSERT INTO hero VALUES (26, 'Allan Quatermain', 'Male', '-', '-', '-', -99, 'Wildstorm', '-', 'good', -99);
INSERT INTO hero VALUES (27, 'Amazo', 'Male', 'red', 'Android', '-', 257, 'DC Comics', '-', 'bad', 173);
INSERT INTO hero VALUES (28, 'Ammo', 'Male', 'brown', 'Human', 'Black', 188, 'Marvel Comics', '-', 'bad', 101);
INSERT INTO hero VALUES (29, 'Ando Masahashi', 'Male', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (30, 'Angel', 'Male', 'blue', '-', 'Blond', 183, 'Marvel Comics', '-', 'good', 68);
INSERT INTO hero VALUES (31, 'Angel', 'Male', '-', 'Vampire', '-', -99, 'Dark Horse Comics', '-', 'good', -99);
INSERT INTO hero VALUES (32, 'Angel Dust', 'Female', 'yellow', 'Mutant', 'Black', 165, 'Marvel Comics', '-', 'good', 57);
INSERT INTO hero VALUES (33, 'Angel Salvadore', 'Female', 'brown', '-', 'Black', 163, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (34, 'Angela', 'Female', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (35, 'Animal Man', 'Male', 'blue', 'Human', 'Blond', 183, 'DC Comics', '-', 'good', 83);
INSERT INTO hero VALUES (36, 'Annihilus', 'Male', 'green', '-', 'No Hair', 180, 'Marvel Comics', '-', 'bad', 90);
INSERT INTO hero VALUES (37, 'Ant-Man', 'Male', 'blue', 'Human', 'Blond', 211, 'Marvel Comics', '-', 'good', 122);
INSERT INTO hero VALUES (38, 'Ant-Man II', 'Male', 'blue', 'Human', 'Blond', 183, 'Marvel Comics', '-', 'good', 86);
INSERT INTO hero VALUES (39, 'Anti-Monitor', 'Male', 'yellow', 'God / Eternal', 'No Hair', 61, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (40, 'Anti-Spawn', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (41, 'Anti-Venom', 'Male', 'blue', 'Symbiote', 'Blond', 229, 'Marvel Comics', '-', '-', 358);
INSERT INTO hero VALUES (42, 'Apocalypse', 'Male', 'red', 'Mutant', 'Black', 213, 'Marvel Comics', 'grey', 'bad', 135);
INSERT INTO hero VALUES (43, 'Aquababy', 'Male', 'blue', '-', 'Blond', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (44, 'Aqualad', 'Male', 'blue', 'Atlantean', 'Black', 178, 'DC Comics', '-', 'good', 106);
INSERT INTO hero VALUES (45, 'Aquaman', 'Male', 'blue', 'Atlantean', 'Blond', 185, 'DC Comics', '-', 'good', 146);
INSERT INTO hero VALUES (46, 'Arachne', 'Female', 'blue', 'Human', 'Blond', 175, 'Marvel Comics', '-', 'good', 63);
INSERT INTO hero VALUES (47, 'Archangel', 'Male', 'blue', 'Mutant', 'Blond', 183, 'Marvel Comics', 'blue', 'good', 68);
INSERT INTO hero VALUES (48, 'Arclight', 'Female', 'violet', '-', 'Purple', 173, 'Marvel Comics', '-', 'bad', 57);
INSERT INTO hero VALUES (49, 'Ardina', 'Female', 'white', 'Alien', 'Orange', 193, 'Marvel Comics', 'gold', 'good', 98);
INSERT INTO hero VALUES (50, 'Ares', 'Male', 'brown', '-', 'Brown', 185, 'Marvel Comics', '-', 'good', 270);
INSERT INTO hero VALUES (51, 'Ariel', 'Female', 'purple', '-', 'Pink', 165, 'Marvel Comics', '-', 'good', 59);
INSERT INTO hero VALUES (52, 'Armor', 'Female', 'black', '-', 'Black', 163, 'Marvel Comics', '-', 'good', 50);
INSERT INTO hero VALUES (53, 'Arsenal', 'Male', '-', 'Human', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (54, 'Astro Boy', 'Male', 'brown', '-', 'Black', -99, NULL, '-', 'good', -99);
INSERT INTO hero VALUES (55, 'Atlas', 'Male', 'brown', 'Mutant', 'Red', 183, 'Marvel Comics', '-', 'good', 101);
INSERT INTO hero VALUES (56, 'Atlas', 'Male', 'blue', 'God / Eternal', 'Brown', 198, 'DC Comics', '-', 'bad', 126);
INSERT INTO hero VALUES (57, 'Atom', 'Male', 'blue', '-', 'Red', 178, 'DC Comics', '-', 'good', 68);
INSERT INTO hero VALUES (58, 'Atom', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (59, 'Atom Girl', 'Female', 'black', '-', 'Black', 168, 'DC Comics', '-', 'good', 54);
INSERT INTO hero VALUES (60, 'Atom II', 'Male', 'brown', 'Human', 'Auburn', 183, 'DC Comics', '-', 'good', 81);
INSERT INTO hero VALUES (61, 'Atom III', 'Male', '-', '-', 'Red', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (62, 'Atom IV', 'Male', 'brown', '-', 'Black', -99, 'DC Comics', '-', 'good', 72);
INSERT INTO hero VALUES (63, 'Aurora', 'Female', 'blue', 'Mutant', 'Black', 180, 'Marvel Comics', '-', 'good', 63);
INSERT INTO hero VALUES (64, 'Azazel', 'Male', 'yellow', 'Neyaphem', 'Black', 183, 'Marvel Comics', 'red', 'bad', 67);
INSERT INTO hero VALUES (65, 'Azrael', 'Male', 'brown', 'Human', 'Black', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (66, 'Aztar', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (67, 'Bane', 'Male', '-', 'Human', '-', 203, 'DC Comics', '-', 'bad', 180);
INSERT INTO hero VALUES (68, 'Banshee', 'Male', 'green', 'Human', 'Strawberry Blond', 183, 'Marvel Comics', '-', 'good', 77);
INSERT INTO hero VALUES (69, 'Bantam', 'Male', 'brown', '-', 'Black', 165, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (70, 'Batgirl', 'Female', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (71, 'Batgirl', 'Female', 'green', 'Human', 'Red', 170, 'DC Comics', '-', 'good', 57);
INSERT INTO hero VALUES (72, 'Batgirl III', 'Female', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (73, 'Batgirl IV', 'Female', 'green', 'Human', 'Black', 165, 'DC Comics', '-', 'good', 52);
INSERT INTO hero VALUES (74, 'Batgirl V', 'Female', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (75, 'Batgirl VI', 'Female', 'blue', '-', 'Blond', 168, 'DC Comics', '-', 'good', 61);
INSERT INTO hero VALUES (76, 'Batman', 'Male', 'blue', 'Human', 'black', 188, 'DC Comics', '-', 'good', 95);
INSERT INTO hero VALUES (77, 'Batman', 'Male', 'blue', 'Human', 'Black', 178, 'DC Comics', '-', 'good', 77);
INSERT INTO hero VALUES (78, 'Batman II', 'Male', 'blue', 'Human', 'Black', 178, 'DC Comics', '-', 'good', 79);
INSERT INTO hero VALUES (79, 'Battlestar', 'Male', 'brown', '-', 'Black', 198, 'Marvel Comics', '-', 'good', 133);
INSERT INTO hero VALUES (80, 'Batwoman V', 'Female', 'green', 'Human', 'Red', 178, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (81, 'Beak', 'Male', 'black', '-', 'White', 175, 'Marvel Comics', '-', 'good', 63);
INSERT INTO hero VALUES (82, 'Beast', 'Male', 'blue', 'Mutant', 'Blue', 180, 'Marvel Comics', 'blue', 'good', 181);
INSERT INTO hero VALUES (83, 'Beast Boy', 'Male', 'green', 'Human', 'Green', 173, 'DC Comics', 'green', 'good', 68);
INSERT INTO hero VALUES (84, 'Beetle', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (85, 'Ben 10', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (86, 'Beta Ray Bill', 'Male', '-', '-', 'No Hair', 201, 'Marvel Comics', '-', 'good', 216);
INSERT INTO hero VALUES (87, 'Beyonder', 'Male', '-', 'God / Eternal', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (88, 'Big Barda', 'Female', 'blue', 'New God', 'Black', 188, 'DC Comics', '-', 'bad', 135);
INSERT INTO hero VALUES (89, 'Big Daddy', 'Male', '-', '-', '-', -99, 'Icon Comics', '-', 'good', -99);
INSERT INTO hero VALUES (90, 'Big Man', 'Male', 'blue', '-', 'Brown', 165, 'Marvel Comics', '-', 'bad', 71);
INSERT INTO hero VALUES (91, 'Bill Harken', 'Male', '-', 'Alpha', '-', -99, 'SyFy', '-', 'good', -99);
INSERT INTO hero VALUES (92, 'Billy Kincaid', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (93, 'Binary', 'Female', 'blue', '-', 'Blond', 180, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (94, 'Bionic Woman', 'Female', 'blue', 'Cyborg', 'Black', -99, NULL, '-', 'good', -99);
INSERT INTO hero VALUES (95, 'Bird-Brain', '-', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (96, 'Bird-Man', 'Male', '-', 'Human', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (97, 'Bird-Man II', 'Male', '-', 'Human', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (98, 'Birdman', 'Male', '-', 'God / Eternal', '-', -99, 'Hanna-Barbera', '-', 'good', -99);
INSERT INTO hero VALUES (99, 'Bishop', 'Male', 'brown', 'Mutant', 'No Hair', 198, 'Marvel Comics', '-', 'good', 124);
INSERT INTO hero VALUES (100, 'Bizarro', 'Male', 'black', 'Bizarro', 'Black', 191, 'DC Comics', 'white', 'neutral', 155);
INSERT INTO hero VALUES (101, 'Black Abbott', 'Male', 'red', '-', 'Black', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (102, 'Black Adam', 'Male', 'brown', '-', 'Black', 191, 'DC Comics', '-', 'bad', 113);
INSERT INTO hero VALUES (103, 'Black Bolt', 'Male', 'blue', 'Inhuman', 'Black', 188, 'Marvel Comics', '-', 'good', 95);
INSERT INTO hero VALUES (104, 'Black Canary', 'Female', 'blue', 'Human', 'Blond', 165, 'DC Comics', '-', 'good', 58);
INSERT INTO hero VALUES (105, 'Black Canary', 'Female', 'blue', 'Metahuman', 'Blond', 170, 'DC Comics', '-', 'good', 59);
INSERT INTO hero VALUES (106, 'Black Cat', 'Female', 'green', 'Human', 'Blond', 178, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (107, 'Black Flash', 'Male', '-', 'God / Eternal', '-', -99, 'DC Comics', '-', 'neutral', -99);
INSERT INTO hero VALUES (108, 'Black Goliath', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (109, 'Black Knight III', 'Male', 'brown', 'Human', 'Brown', 183, 'Marvel Comics', '-', 'good', 86);
INSERT INTO hero VALUES (110, 'Black Lightning', 'Male', 'brown', '-', 'No Hair', 185, 'DC Comics', '-', 'good', 90);
INSERT INTO hero VALUES (111, 'Black Mamba', 'Female', 'green', '-', 'Black', 170, 'Marvel Comics', '-', 'bad', 52);
INSERT INTO hero VALUES (112, 'Black Manta', 'Male', 'black', 'Human', 'No Hair', 188, 'DC Comics', '-', 'bad', 92);
INSERT INTO hero VALUES (113, 'Black Panther', 'Male', 'brown', 'Human', 'Black', 183, 'Marvel Comics', '-', 'good', 90);
INSERT INTO hero VALUES (114, 'Black Widow', 'Female', 'green', 'Human', 'Auburn', 170, 'Marvel Comics', '-', 'good', 59);
INSERT INTO hero VALUES (115, 'Black Widow II', 'Female', 'blue', '-', 'Blond', 170, 'Marvel Comics', '-', 'good', 61);
INSERT INTO hero VALUES (116, 'Blackout', 'Male', 'red', 'Demon', 'White', 191, 'Marvel Comics', 'white', 'bad', 104);
INSERT INTO hero VALUES (117, 'Blackwing', 'Male', 'blue', '-', 'Black', 185, 'Marvel Comics', '-', 'bad', 86);
INSERT INTO hero VALUES (118, 'Blackwulf', 'Male', 'red', 'Alien', 'White', 188, 'Marvel Comics', '-', '-', 88);
INSERT INTO hero VALUES (119, 'Blade', 'Male', 'brown', 'Vampire', 'Black', 188, 'Marvel Comics', '-', 'good', 97);
INSERT INTO hero VALUES (120, 'Blaquesmith', '-', 'black', '-', 'No Hair', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (121, 'Bling!', 'Female', '-', '-', '-', 168, 'Marvel Comics', '-', 'good', 68);
INSERT INTO hero VALUES (122, 'Blink', 'Female', 'green', 'Mutant', 'Magenta', 165, 'Marvel Comics', 'pink', 'good', 56);
INSERT INTO hero VALUES (123, 'Blizzard', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (124, 'Blizzard', 'Male', '-', '-', 'Brown', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (125, 'Blizzard II', 'Male', 'brown', '-', 'Brown', 175, 'Marvel Comics', '-', 'bad', 77);
INSERT INTO hero VALUES (126, 'Blob', 'Male', 'brown', '-', 'Brown', 178, 'Marvel Comics', '-', 'bad', 230);
INSERT INTO hero VALUES (127, 'Bloodaxe', 'Female', 'blue', 'Human', 'Brown', 218, 'Marvel Comics', '-', 'bad', 495);
INSERT INTO hero VALUES (128, 'Bloodhawk', 'Male', 'black', 'Mutant', 'No Hair', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (129, 'Bloodwraith', 'Male', 'white', '-', 'No Hair', 30.5, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (130, 'Blue Beetle', 'Male', 'blue', '-', 'Brown', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (131, 'Blue Beetle', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (132, 'Blue Beetle II', 'Male', 'blue', '-', 'Brown', 183, 'DC Comics', '-', 'good', 86);
INSERT INTO hero VALUES (133, 'Blue Beetle III', 'Male', 'brown', 'Human', 'Black', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (134, 'Boba Fett', 'Male', 'brown', 'Human / Clone', 'Black', 183, 'George Lucas', '-', 'bad', -99);
INSERT INTO hero VALUES (135, 'Bolt', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (136, 'Bomb Queen', 'Female', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (137, 'Boom-Boom', 'Female', 'blue', 'Mutant', 'Blond', 165, 'Marvel Comics', '-', 'good', 55);
INSERT INTO hero VALUES (138, 'Boomer', 'Female', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (139, 'Booster Gold', 'Male', 'blue', 'Human', 'Blond', 196, 'DC Comics', '-', 'good', 97);
INSERT INTO hero VALUES (140, 'Box', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (141, 'Box III', '-', 'blue', '-', 'Blond', 193, 'Marvel Comics', '-', 'good', 110);
INSERT INTO hero VALUES (142, 'Box IV', '-', 'brown', '-', 'Brown / Black', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (143, 'Brainiac', 'Male', 'green', 'Android', 'No Hair', 198, 'DC Comics', 'green', 'bad', 135);
INSERT INTO hero VALUES (144, 'Brainiac 5', 'Male', 'green', '-', 'Blond', 170, 'DC Comics', '-', 'good', 61);
INSERT INTO hero VALUES (145, 'Brother Voodoo', 'Male', 'brown', 'Human', 'Brown / White', 183, 'Marvel Comics', '-', 'good', 99);
INSERT INTO hero VALUES (146, 'Brundlefly', 'Male', '-', 'Mutant', '-', 193, NULL, '-', '-', -99);
INSERT INTO hero VALUES (147, 'Buffy', 'Female', 'green', 'Human', 'Blond', 157, 'Dark Horse Comics', '-', 'good', 52);
INSERT INTO hero VALUES (148, 'Bullseye', 'Male', 'blue', 'Human', 'blond', 183, 'Marvel Comics', '-', 'bad', 90);
INSERT INTO hero VALUES (149, 'Bumblebee', 'Female', 'brown', 'Human', 'Black', 170, 'DC Comics', '-', 'good', 59);
INSERT INTO hero VALUES (150, 'Bumbleboy', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (151, 'Bushido', 'Male', '-', 'Human', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (152, 'Cable', 'Male', 'blue', 'Mutant', 'White', 203, 'Marvel Comics', '-', 'good', 158);
INSERT INTO hero VALUES (153, 'Callisto', 'Female', 'blue', '-', 'Black', 175, 'Marvel Comics', '-', 'bad', 74);
INSERT INTO hero VALUES (154, 'Cameron Hicks', 'Male', '-', 'Alpha', '-', -99, 'SyFy', '-', 'good', -99);
INSERT INTO hero VALUES (155, 'Cannonball', 'Male', 'blue', '-', 'Blond', 183, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (156, 'Captain America', 'Male', 'blue', 'Human', 'blond', 188, 'Marvel Comics', '-', 'good', 108);
INSERT INTO hero VALUES (157, 'Captain Atom', 'Male', 'blue', 'Human / Radiation', 'Silver', 193, 'DC Comics', 'silver', 'good', 90);
INSERT INTO hero VALUES (158, 'Captain Britain', 'Male', 'blue', 'Human', 'Blond', 198, 'Marvel Comics', '-', 'good', 116);
INSERT INTO hero VALUES (159, 'Captain Cold', 'Male', 'brown', 'Human', 'Brown', -99, 'DC Comics', '-', 'neutral', -99);
INSERT INTO hero VALUES (160, 'Captain Epic', 'Male', 'blue', '-', 'Brown', 188, 'Team Epic TV', '-', 'good', -99);
INSERT INTO hero VALUES (161, 'Captain Hindsight', 'Male', '-', 'Human', 'Black', -99, 'South Park', '-', 'good', -99);
INSERT INTO hero VALUES (162, 'Captain Mar-vell', 'Male', 'blue', '-', 'Blond', 188, 'Marvel Comics', '-', 'good', 108);
INSERT INTO hero VALUES (163, 'Captain Marvel', 'Female', 'blue', 'Human-Kree', 'Blond', 180, 'Marvel Comics', '-', 'good', 74);
INSERT INTO hero VALUES (164, 'Captain Marvel', 'Male', 'blue', 'Human', 'Black', 193, 'DC Comics', '-', 'good', 101);
INSERT INTO hero VALUES (165, 'Captain Marvel II', 'Male', 'blue', 'Human', 'Black', 175, 'DC Comics', '-', 'good', 74);
INSERT INTO hero VALUES (166, 'Captain Midnight', 'Male', '-', 'Human', '-', -99, 'Dark Horse Comics', '-', 'good', -99);
INSERT INTO hero VALUES (167, 'Captain Planet', 'Male', 'red', 'God / Eternal', 'Green', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (168, 'Captain Universe', '-', '-', 'God / Eternal', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (169, 'Carnage', 'Male', 'green', 'Symbiote', 'Red', 185, 'Marvel Comics', '-', 'bad', 86);
INSERT INTO hero VALUES (170, 'Cat', 'Female', 'blue', '-', 'Blond', 173, 'Marvel Comics', '-', 'good', 61);
INSERT INTO hero VALUES (171, 'Cat II', 'Female', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (172, 'Catwoman', 'Female', 'green', 'Human', 'Black', 175, 'DC Comics', '-', 'good', 61);
INSERT INTO hero VALUES (173, 'Cecilia Reyes', '-', 'brown', '-', 'Brown', 170, 'Marvel Comics', '-', 'good', 62);
INSERT INTO hero VALUES (174, 'Century', 'Male', 'white', 'Alien', 'White', 201, 'Marvel Comics', 'grey', 'good', 97);
INSERT INTO hero VALUES (175, 'Cerebra', 'Female', '-', 'Mutant', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (176, 'Chamber', 'Male', 'brown', 'Mutant', 'Brown', 175, 'Marvel Comics', '-', 'good', 63);
INSERT INTO hero VALUES (177, 'Chameleon', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (178, 'Changeling', 'Male', 'brown', '-', 'Black', 180, 'Marvel Comics', '-', 'bad', 81);
INSERT INTO hero VALUES (179, 'Cheetah', 'Female', 'green', 'Human', 'Blond', 163, 'DC Comics', '-', 'bad', 50);
INSERT INTO hero VALUES (180, 'Cheetah II', 'Female', 'green', 'Human', 'Brown', 170, 'DC Comics', '-', 'bad', 55);
INSERT INTO hero VALUES (181, 'Cheetah III', 'Female', 'brown', 'Human', 'Brown', 175, 'DC Comics', '-', 'bad', 54);
INSERT INTO hero VALUES (182, 'Chromos', 'Male', 'brown', '-', 'Red / Grey', 185, 'Team Epic TV', '-', 'bad', 86);
INSERT INTO hero VALUES (183, 'Chuck Norris', 'Male', '-', '-', '-', 178, NULL, '-', 'good', -99);
INSERT INTO hero VALUES (184, 'Citizen Steel', 'Male', 'green', 'Human', 'Red', 183, 'DC Comics', '-', 'good', 170);
INSERT INTO hero VALUES (185, 'Claire Bennet', 'Female', 'blue', '-', 'Blond', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (186, 'Clea', '-', '-', '-', 'White', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (187, 'Cloak', 'Male', 'brown', '-', 'black', 226, 'Marvel Comics', '-', 'good', 70);
INSERT INTO hero VALUES (188, 'Clock King', 'Male', 'blue', 'Human', 'Black', 178, 'DC Comics', '-', 'bad', 78);
INSERT INTO hero VALUES (189, 'Cogliostro', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (190, 'Colin Wagner', 'Male', 'grey', '-', 'Brown', -99, 'HarperCollins', '-', 'good', -99);
INSERT INTO hero VALUES (191, 'Colossal Boy', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (192, 'Colossus', 'Male', 'silver', 'Mutant', 'Black', 226, 'Marvel Comics', '-', 'good', 225);
INSERT INTO hero VALUES (193, 'Copycat', 'Female', 'red', 'Mutant', 'White', 183, 'Marvel Comics', 'blue', 'neutral', 67);
INSERT INTO hero VALUES (194, 'Corsair', 'Male', 'brown', '-', 'Brown', 191, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (195, 'Cottonmouth', 'Male', 'brown', 'Human', 'Black', 183, 'Marvel Comics', '-', 'bad', 99);
INSERT INTO hero VALUES (196, 'Crimson Crusader', 'Male', 'blue', '-', 'Strawberry Blond', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (197, 'Crimson Dynamo', 'Male', 'brown', '-', 'No Hair', 180, 'Marvel Comics', '-', 'good', 104);
INSERT INTO hero VALUES (198, 'Crystal', 'Female', 'green', 'Inhuman', 'Red', 168, 'Marvel Comics', '-', 'good', 50);
INSERT INTO hero VALUES (199, 'Curse', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (200, 'Cy-Gor', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (201, 'Cyborg', 'Male', 'brown', 'Cyborg', 'Black', 198, 'DC Comics', '-', 'good', 173);
INSERT INTO hero VALUES (202, 'Cyborg Superman', 'Male', 'blue', 'Cyborg', 'Black', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (203, 'Cyclops', 'Male', 'brown', 'Mutant', 'Brown', 191, 'Marvel Comics', '-', 'good', 88);
INSERT INTO hero VALUES (204, 'Cypher', '-', 'blue', '-', 'Blond', 175, 'Marvel Comics', '-', 'good', 68);
INSERT INTO hero VALUES (205, 'Dagger', 'Female', 'blue', '-', 'Blond', 165, 'Marvel Comics', '-', 'good', 52);
INSERT INTO hero VALUES (206, 'Danny Cooper', 'Male', 'brown', '-', 'Blond', -99, 'HarperCollins', '-', 'good', -99);
INSERT INTO hero VALUES (207, 'Daphne Powell', 'Female', '-', '-', '-', -99, 'ABC Studios', '-', 'good', -99);
INSERT INTO hero VALUES (208, 'Daredevil', 'Male', 'blue', 'Human', 'Red', 183, 'Marvel Comics', '-', 'good', 90);
INSERT INTO hero VALUES (209, 'Darkhawk', 'Male', 'brown', 'Human', 'Brown', 185, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (210, 'Darkman', 'Male', '-', '-', '-', -99, 'Universal Studios', '-', 'good', -99);
INSERT INTO hero VALUES (211, 'Darkseid', 'Male', 'red', 'New God', 'No Hair', 267, 'DC Comics', 'grey', 'bad', 817);
INSERT INTO hero VALUES (212, 'Darkside', '-', '-', '-', '-', -99, NULL, '-', 'bad', -99);
INSERT INTO hero VALUES (213, 'Darkstar', 'Female', 'brown', 'Mutant', 'Blond', 168, 'Marvel Comics', '-', 'good', 56);
INSERT INTO hero VALUES (214, 'Darth Maul', 'Male', 'yellow / red', 'Dathomirian Zabrak', '-', 170, 'George Lucas', 'red / black', 'bad', -99);
INSERT INTO hero VALUES (215, 'Darth Vader', 'Male', 'yellow', 'Cyborg', 'No Hair', 198, 'George Lucas', '-', 'bad', 135);
INSERT INTO hero VALUES (216, 'Dash', 'Male', 'blue', 'Human', 'Blond', 122, 'Dark Horse Comics', '-', 'good', 27);
INSERT INTO hero VALUES (217, 'Data', 'Male', 'yellow', 'Android', 'Brown', -99, 'Star Trek', '-', 'good', -99);
INSERT INTO hero VALUES (218, 'Dazzler', 'Female', 'blue', 'Mutant', 'Blond', 173, 'Marvel Comics', '-', 'good', 52);
INSERT INTO hero VALUES (219, 'Deadman', 'Male', 'blue', 'Human', 'Black', 183, 'DC Comics', '-', 'good', 90);
INSERT INTO hero VALUES (220, 'Deadpool', 'Male', 'brown', 'Mutant', 'No Hair', 188, 'Marvel Comics', '-', 'neutral', 95);
INSERT INTO hero VALUES (221, 'Deadshot', 'Male', 'brown', 'Human', 'Brown', 185, 'DC Comics', '-', 'bad', 91);
INSERT INTO hero VALUES (222, 'Deathlok', 'Male', 'brown', 'Cyborg', 'Grey', 193, 'Marvel Comics', '-', 'good', 178);
INSERT INTO hero VALUES (223, 'Deathstroke', 'Male', 'blue', 'Human', 'White', 193, 'DC Comics', '-', 'neutral', 101);
INSERT INTO hero VALUES (224, 'Demogoblin', 'Male', 'red', 'Demon', 'No Hair', 185, 'Marvel Comics', '-', 'bad', 95);
INSERT INTO hero VALUES (225, 'Destroyer', 'Male', '-', '-', '-', 188, 'Marvel Comics', '-', 'bad', 383);
INSERT INTO hero VALUES (226, 'Diamondback', 'Male', 'brown', 'Human', 'Black', 193, 'Marvel Comics', '-', 'bad', 90);
INSERT INTO hero VALUES (227, 'DL Hawkins', 'Male', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (228, 'Doc Samson', 'Male', 'blue', 'Human / Radiation', 'Green', 198, 'Marvel Comics', '-', 'good', 171);
INSERT INTO hero VALUES (229, 'Doctor Doom', 'Male', 'brown', 'Human', 'Brown', 201, 'Marvel Comics', '-', 'bad', 187);
INSERT INTO hero VALUES (230, 'Doctor Doom II', 'Male', 'brown', '-', 'Brown', 201, 'Marvel Comics', '-', 'bad', 132);
INSERT INTO hero VALUES (231, 'Doctor Fate', 'Male', 'blue', 'Human', 'Blond', 188, 'DC Comics', '-', 'good', 89);
INSERT INTO hero VALUES (232, 'Doctor Octopus', 'Male', 'brown', 'Human', 'Brown', 175, 'Marvel Comics', '-', 'bad', 110);
INSERT INTO hero VALUES (233, 'Doctor Strange', 'Male', 'grey', 'Human', 'Black', 188, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (234, 'Domino', 'Female', 'blue', 'Human', 'Black', 173, 'Marvel Comics', 'white', 'good', 54);
INSERT INTO hero VALUES (235, 'Donatello', 'Male', 'green', 'Mutant', 'No Hair', -99, 'IDW Publishing', 'green', 'good', -99);
INSERT INTO hero VALUES (236, 'Donna Troy', 'Female', 'blue', 'Amazon', 'Black', 175, 'DC Comics', '-', 'good', 63);
INSERT INTO hero VALUES (237, 'Doomsday', 'Male', 'red', 'Alien', 'White', 244, 'DC Comics', '-', 'bad', 412);
INSERT INTO hero VALUES (238, 'Doppelganger', 'Male', 'white', '-', 'No Hair', 196, 'Marvel Comics', '-', 'bad', 104);
INSERT INTO hero VALUES (239, 'Dormammu', 'Male', 'yellow', '-', 'No Hair', 185, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (240, 'Dr Manhattan', 'Male', 'white', 'Human / Cosmic', 'No Hair', -99, 'DC Comics', 'blue', 'good', -99);
INSERT INTO hero VALUES (241, 'Drax the Destroyer', 'Male', 'red', 'Human / Altered', 'No Hair', 193, 'Marvel Comics', 'green', 'good', 306);
INSERT INTO hero VALUES (242, 'Ego', '-', '-', '-', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (243, 'Elastigirl', 'Female', 'brown', 'Human', 'Brown', 168, 'Dark Horse Comics', '-', 'good', 56);
INSERT INTO hero VALUES (244, 'Electro', 'Male', 'blue', 'Human', 'Auburn', 180, 'Marvel Comics', '-', 'bad', 74);
INSERT INTO hero VALUES (245, 'Elektra', 'Female', 'blue', 'Human', 'Black', 175, 'Marvel Comics', '-', 'good', 59);
INSERT INTO hero VALUES (246, 'Elle Bishop', 'Female', 'blue', '-', 'Blond', -99, 'NBC - Heroes', '-', 'bad', -99);
INSERT INTO hero VALUES (247, 'Elongated Man', 'Male', 'blue', '-', 'Red', 185, 'DC Comics', '-', 'good', 80);
INSERT INTO hero VALUES (248, 'Emma Frost', 'Female', 'blue', '-', 'Blond', 178, 'Marvel Comics', '-', 'good', 65);
INSERT INTO hero VALUES (249, 'Enchantress', 'Female', 'blue', 'Human', 'Blond', 168, 'DC Comics', '-', 'good', 57);
INSERT INTO hero VALUES (250, 'Energy', 'Female', '-', '-', '-', -99, 'HarperCollins', '-', 'good', -99);
INSERT INTO hero VALUES (251, 'ERG-1', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (252, 'Ethan Hunt', 'Male', 'brown', 'Human', 'Brown', 168, NULL, '-', 'good', -99);
INSERT INTO hero VALUES (253, 'Etrigan', 'Male', 'red', 'Demon', 'No Hair', 193, 'DC Comics', 'yellow', 'neutral', 203);
INSERT INTO hero VALUES (254, 'Evil Deadpool', 'Male', 'white', 'Mutant', 'Red', 188, 'Marvel Comics', '-', 'bad', 95);
INSERT INTO hero VALUES (255, 'Evilhawk', 'Male', 'red', 'Alien', 'Black', 191, 'Marvel Comics', 'green', 'bad', 106);
INSERT INTO hero VALUES (256, 'Exodus', 'Male', 'blue', 'Mutant', 'Black', 183, 'Marvel Comics', 'red', 'bad', 88);
INSERT INTO hero VALUES (257, 'Fabian Cortez', '-', 'blue', '-', 'Brown', 196, 'Marvel Comics', '-', 'bad', 96);
INSERT INTO hero VALUES (258, 'Falcon', 'Male', 'brown', 'Human', 'Black', 188, 'Marvel Comics', '-', 'good', 108);
INSERT INTO hero VALUES (259, 'Fallen One II', 'Male', 'black', '-', 'Blue', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (260, 'Faora', 'Female', '-', 'Kryptonian', '-', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (261, 'Feral', '-', 'yellow (without irises)', '-', 'Orange / White', 175, 'Marvel Comics', '-', 'good', 50);
INSERT INTO hero VALUES (262, 'Fighting Spirit', 'Female', '-', '-', 'Red', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (263, 'Fin Fang Foom', 'Male', 'red', 'Kakarantharaian', 'No Hair', 975, 'Marvel Comics', 'green', 'good', 18);
INSERT INTO hero VALUES (264, 'Firebird', 'Female', 'brown', '-', 'Black', 165, 'Marvel Comics', '-', 'good', 56);
INSERT INTO hero VALUES (265, 'Firelord', '-', 'white', '-', 'Yellow', 193, 'Marvel Comics', '-', 'good', 99);
INSERT INTO hero VALUES (266, 'Firestar', 'Female', 'green', 'Mutant', 'Red', 173, 'Marvel Comics', '-', 'good', 56);
INSERT INTO hero VALUES (267, 'Firestorm', 'Male', 'brown', '-', 'Black', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (268, 'Firestorm', 'Male', 'blue', 'Human', 'Auburn', 188, 'DC Comics', '-', 'good', 91);
INSERT INTO hero VALUES (269, 'Fixer', '-', 'red', '-', 'No Hair', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (270, 'Flash', 'Male', 'blue', 'Human', 'Brown / White', 180, 'DC Comics', '-', 'good', 81);
INSERT INTO hero VALUES (271, 'Flash Gordon', 'Male', '-', '-', '-', -99, NULL, '-', 'good', -99);
INSERT INTO hero VALUES (272, 'Flash II', 'Male', 'blue', 'Human', 'Blond', 183, 'DC Comics', '-', 'good', 88);
INSERT INTO hero VALUES (273, 'Flash III', 'Male', '-', 'Human', '-', 183, 'DC Comics', '-', 'good', 86);
INSERT INTO hero VALUES (274, 'Flash IV', 'Male', 'yellow', 'Human', 'Auburn', 157, 'DC Comics', '-', 'good', 52);
INSERT INTO hero VALUES (275, 'Forge', '-', 'brown', '-', 'Black', 183, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (276, 'Franklin Richards', 'Male', 'blue', 'Mutant', 'Blond', 142, 'Marvel Comics', '-', 'good', 45);
INSERT INTO hero VALUES (277, 'Franklin Storm', '-', 'blue', '-', 'Grey', 188, 'Marvel Comics', '-', 'good', 92);
INSERT INTO hero VALUES (278, 'Frenzy', 'Female', 'brown', '-', 'Black', 211, 'Marvel Comics', '-', 'bad', 104);
INSERT INTO hero VALUES (279, 'Frigga', 'Female', 'blue', '-', 'White', 180, 'Marvel Comics', '-', 'good', 167);
INSERT INTO hero VALUES (280, 'Galactus', 'Male', 'black', 'Cosmic Entity', 'Black', 876, 'Marvel Comics', '-', 'neutral', 16);
INSERT INTO hero VALUES (281, 'Gambit', 'Male', 'red', 'Mutant', 'Brown', 185, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (282, 'Gamora', 'Female', 'yellow', 'Zen-Whoberian', 'Black', 183, 'Marvel Comics', 'green', 'good', 77);
INSERT INTO hero VALUES (283, 'Garbage Man', 'Male', '-', 'Mutant', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (284, 'Gary Bell', 'Male', '-', 'Alpha', '-', -99, 'SyFy', '-', 'good', -99);
INSERT INTO hero VALUES (285, 'General Zod', 'Male', 'black', 'Kryptonian', 'Black', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (286, 'Genesis', 'Male', 'blue', '-', 'Blond', 185, 'Marvel Comics', '-', 'good', 86);
INSERT INTO hero VALUES (287, 'Ghost Rider', 'Male', 'red', 'Demon', 'No Hair', 188, 'Marvel Comics', '-', 'good', 99);
INSERT INTO hero VALUES (288, 'Ghost Rider II', '-', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (289, 'Giant-Man', 'Male', '-', 'Human', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (290, 'Giant-Man II', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (291, 'Giganta', 'Female', 'green', '-', 'Red', 62.5, 'DC Comics', '-', 'bad', 630);
INSERT INTO hero VALUES (292, 'Gladiator', 'Male', 'blue', 'Strontian', 'Blue', 198, 'Marvel Comics', 'purple', 'neutral', 268);
INSERT INTO hero VALUES (293, 'Goblin Queen', 'Female', 'green', '-', 'Red', 168, 'Marvel Comics', '-', 'bad', 50);
INSERT INTO hero VALUES (294, 'Godzilla', '-', '-', 'Kaiju', '-', 108, NULL, 'grey', 'bad', NULL);
INSERT INTO hero VALUES (295, 'Gog', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (296, 'Goku', 'Male', '-', 'Saiyan', '-', 175, 'Shueisha', '-', 'good', 62);
INSERT INTO hero VALUES (297, 'Goliath', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (298, 'Goliath', 'Male', '-', 'Human', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (299, 'Goliath', 'Male', '-', 'Human', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (300, 'Goliath IV', 'Male', 'brown', '-', 'Black', 183, 'Marvel Comics', '-', 'good', 90);
INSERT INTO hero VALUES (301, 'Gorilla Grodd', 'Male', 'yellow', 'Gorilla', 'Black', 198, 'DC Comics', '-', 'bad', 270);
INSERT INTO hero VALUES (302, 'Granny Goodness', 'Female', 'blue', '-', 'White', 178, 'DC Comics', '-', 'bad', 115);
INSERT INTO hero VALUES (303, 'Gravity', 'Male', 'blue', 'Human', 'Brown', 178, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (304, 'Greedo', 'Male', 'purple', 'Rodian', '-', 170, 'George Lucas', 'green', 'bad', -99);
INSERT INTO hero VALUES (305, 'Green Arrow', 'Male', 'green', 'Human', 'Blond', 188, 'DC Comics', '-', 'good', 88);
INSERT INTO hero VALUES (306, 'Green Goblin', 'Male', 'blue', 'Human', 'Auburn', 180, 'Marvel Comics', '-', 'bad', 83);
INSERT INTO hero VALUES (307, 'Green Goblin II', 'Male', 'blue', '-', 'Auburn', 178, 'Marvel Comics', '-', 'bad', 77);
INSERT INTO hero VALUES (308, 'Green Goblin III', 'Male', '-', '-', '-', 183, 'Marvel Comics', '-', 'good', 88);
INSERT INTO hero VALUES (309, 'Green Goblin IV', 'Male', 'green', '-', 'Brown', 178, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (310, 'Groot', 'Male', 'yellow', 'Flora Colossus', '-', 701, 'Marvel Comics', '-', 'good', 4);
INSERT INTO hero VALUES (311, 'Guardian', 'Male', 'brown', 'Human', 'Black', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (312, 'Guy Gardner', 'Male', 'blue', 'Human-Vuldarian', 'Red', 188, 'DC Comics', '-', 'good', 95);
INSERT INTO hero VALUES (313, 'Hal Jordan', 'Male', 'brown', 'Human', 'Brown', 188, 'DC Comics', '-', 'good', 90);
INSERT INTO hero VALUES (314, 'Han Solo', 'Male', 'brown', 'Human', 'Brown', 183, 'George Lucas', '-', 'good', 79);
INSERT INTO hero VALUES (315, 'Hancock', 'Male', 'brown', 'Human', 'Black', 188, 'Sony Pictures', '-', 'good', -99);
INSERT INTO hero VALUES (316, 'Harley Quinn', 'Female', 'blue', 'Human', 'Blond', 170, 'DC Comics', '-', 'bad', 63);
INSERT INTO hero VALUES (317, 'Harry Potter', 'Male', 'green', 'Human', 'Black', -99, 'J. K. Rowling', '-', 'good', -99);
INSERT INTO hero VALUES (318, 'Havok', 'Male', 'blue', 'Mutant', 'Blond', 183, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (319, 'Hawk', 'Male', 'red', '-', 'Brown', 185, 'DC Comics', '-', 'good', 89);
INSERT INTO hero VALUES (320, 'Hawkeye', 'Male', 'blue', 'Human', 'Blond', 191, 'Marvel Comics', '-', 'good', 104);
INSERT INTO hero VALUES (321, 'Hawkeye II', 'Female', 'blue', 'Human', 'Black', 165, 'Marvel Comics', '-', 'good', 57);
INSERT INTO hero VALUES (322, 'Hawkgirl', 'Female', 'green', '-', 'Red', 175, 'DC Comics', '-', 'good', 61);
INSERT INTO hero VALUES (323, 'Hawkman', 'Male', 'blue', '-', 'Brown', 185, 'DC Comics', '-', 'good', 88);
INSERT INTO hero VALUES (324, 'Hawkwoman', 'Female', 'green', '-', 'Red', 175, 'DC Comics', '-', 'good', 54);
INSERT INTO hero VALUES (325, 'Hawkwoman II', 'Female', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (326, 'Hawkwoman III', 'Female', 'blue', '-', 'Red', 170, 'DC Comics', '-', 'good', 65);
INSERT INTO hero VALUES (327, 'Heat Wave', 'Male', 'blue', 'Human', 'No Hair', 180, 'DC Comics', '-', 'bad', 81);
INSERT INTO hero VALUES (328, 'Hela', 'Female', 'green', 'Asgardian', 'Black', 213, 'Marvel Comics', '-', 'bad', 225);
INSERT INTO hero VALUES (329, 'Hellboy', 'Male', 'gold', 'Demon', 'Black', 259, 'Dark Horse Comics', '-', 'good', 158);
INSERT INTO hero VALUES (330, 'Hellcat', 'Female', 'blue', 'Human', 'Red', 173, 'Marvel Comics', '-', 'good', 61);
INSERT INTO hero VALUES (331, 'Hellstorm', 'Male', 'red', '-', 'Red', 185, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (332, 'Hercules', 'Male', 'blue', 'Demi-God', 'Brown', 196, 'Marvel Comics', '-', 'good', 146);
INSERT INTO hero VALUES (333, 'Hiro Nakamura', 'Male', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (334, 'Hit-Girl', 'Female', '-', 'Human', '-', -99, 'Icon Comics', '-', 'good', -99);
INSERT INTO hero VALUES (335, 'Hobgoblin', 'Male', 'blue', '-', 'Grey', 180, 'Marvel Comics', '-', 'bad', 83);
INSERT INTO hero VALUES (336, 'Hollow', 'Female', 'blue', '-', 'Red', 170, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (337, 'Hope Summers', 'Female', 'green', '-', 'Red', 168, 'Marvel Comics', '-', 'good', 48);
INSERT INTO hero VALUES (338, 'Howard the Duck', 'Male', 'brown', '-', 'Yellow', 79, 'Marvel Comics', '-', 'good', 18);
INSERT INTO hero VALUES (339, 'Hulk', 'Male', 'green', 'Human / Radiation', 'Green', 244, 'Marvel Comics', 'green', 'good', 630);
INSERT INTO hero VALUES (340, 'Human Torch', 'Male', 'blue', 'Human / Radiation', 'Blond', 178, 'Marvel Comics', '-', 'good', 77);
INSERT INTO hero VALUES (341, 'Huntress', 'Female', 'blue', '-', 'Black', 180, 'DC Comics', '-', 'good', 59);
INSERT INTO hero VALUES (342, 'Husk', 'Female', 'blue', 'Mutant', 'Blond', 170, 'Marvel Comics', '-', 'good', 58);
INSERT INTO hero VALUES (343, 'Hybrid', 'Male', 'brown', 'Symbiote', 'Black', 175, 'Marvel Comics', '-', 'good', 77);
INSERT INTO hero VALUES (344, 'Hydro-Man', 'Male', 'brown', '-', 'Brown', 188, 'Marvel Comics', '-', 'bad', 119);
INSERT INTO hero VALUES (345, 'Hyperion', 'Male', 'blue', 'Eternal', 'Red', 183, 'Marvel Comics', '-', 'good', 207);
INSERT INTO hero VALUES (346, 'Iceman', 'Male', 'brown', 'Mutant', 'Brown', 173, 'Marvel Comics', '-', 'good', 65);
INSERT INTO hero VALUES (347, 'Impulse', 'Male', 'yellow', 'Human', 'Auburn', 170, 'DC Comics', '-', 'good', 65);
INSERT INTO hero VALUES (348, 'Indiana Jones', 'Male', '-', 'Human', '-', 183, 'George Lucas', '-', 'good', 79);
INSERT INTO hero VALUES (349, 'Indigo', 'Female', '-', 'Alien', 'Purple', -99, 'DC Comics', '-', 'neutral', -99);
INSERT INTO hero VALUES (350, 'Ink', 'Male', 'blue', 'Mutant', 'No Hair', 180, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (351, 'Invisible Woman', 'Female', 'blue', 'Human / Radiation', 'Blond', 168, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (352, 'Iron Fist', 'Male', 'blue', 'Human', 'Blond', 180, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (353, 'Iron Man', 'Male', 'blue', 'Human', 'Black', 198, 'Marvel Comics', '-', 'good', 191);
INSERT INTO hero VALUES (354, 'Iron Monger', 'Male', 'blue', '-', 'No Hair', -99, 'Marvel Comics', '-', 'bad', 2);
INSERT INTO hero VALUES (355, 'Isis', 'Female', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (356, 'Jack Bauer', 'Male', '-', '-', '-', -99, NULL, '-', 'good', -99);
INSERT INTO hero VALUES (357, 'Jack of Hearts', 'Male', 'blue / white', 'Human', 'Brown', 155, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (358, 'Jack-Jack', 'Male', 'blue', 'Human', 'Brown', 71, 'Dark Horse Comics', '-', 'good', 14);
INSERT INTO hero VALUES (359, 'James Bond', 'Male', 'blue', 'Human', 'Blond', 183, 'Titan Books', '-', 'good', -99);
INSERT INTO hero VALUES (360, 'James T. Kirk', 'Male', 'hazel', 'Human', 'Brown', 178, 'Star Trek', '-', 'good', 77);
INSERT INTO hero VALUES (361, 'Jar Jar Binks', 'Male', 'yellow', 'Gungan', '-', 193, 'George Lucas', 'orange / white', 'good', -99);
INSERT INTO hero VALUES (362, 'Jason Bourne', 'Male', '-', 'Human', '-', -99, NULL, '-', 'good', -99);
INSERT INTO hero VALUES (363, 'Jean Grey', 'Female', 'green', 'Mutant', 'Red', 168, 'Marvel Comics', '-', 'good', 52);
INSERT INTO hero VALUES (364, 'Jean-Luc Picard', 'Male', '-', 'Human', '-', -99, 'Star Trek', '-', 'good', -99);
INSERT INTO hero VALUES (365, 'Jennifer Kale', 'Female', 'blue', '-', 'Blond', 168, 'Marvel Comics', '-', 'good', 55);
INSERT INTO hero VALUES (366, 'Jesse Quick', 'Female', '-', 'Human', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (367, 'Jessica Cruz', 'Female', 'green', 'Human', 'Brown', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (368, 'Jessica Jones', 'Female', 'brown', 'Human', 'Brown', 170, 'Marvel Comics', '-', 'good', 56);
INSERT INTO hero VALUES (369, 'Jessica Sanders', 'Female', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (370, 'Jigsaw', 'Male', 'blue', '-', 'Black', 188, 'Marvel Comics', '-', 'bad', 113);
INSERT INTO hero VALUES (371, 'Jim Powell', 'Male', '-', '-', '-', -99, 'ABC Studios', '-', 'good', -99);
INSERT INTO hero VALUES (372, 'JJ Powell', 'Male', '-', '-', '-', -99, 'ABC Studios', '-', 'good', -99);
INSERT INTO hero VALUES (373, 'Johann Krauss', 'Male', '-', '-', '-', -99, 'Dark Horse Comics', '-', 'good', -99);
INSERT INTO hero VALUES (374, 'John Constantine', 'Male', 'blue', 'Human', 'Blond', 183, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (375, 'John Stewart', 'Male', 'green', 'Human', 'Black', 185, 'DC Comics', '-', 'good', 90);
INSERT INTO hero VALUES (376, 'John Wraith', 'Male', 'brown', '-', 'Black', 183, 'Marvel Comics', '-', 'good', 88);
INSERT INTO hero VALUES (377, 'Joker', 'Male', 'green', 'Human', 'Green', 196, 'DC Comics', 'white', 'bad', 86);
INSERT INTO hero VALUES (378, 'Jolt', 'Female', 'blue', '-', 'Black', 165, 'Marvel Comics', '-', 'good', 49);
INSERT INTO hero VALUES (379, 'Jubilee', 'Female', 'red', 'Mutant', 'Black', 165, 'Marvel Comics', '-', 'good', 52);
INSERT INTO hero VALUES (380, 'Judge Dredd', 'Male', '-', 'Human', '-', 188, 'Rebellion', '-', 'good', -99);
INSERT INTO hero VALUES (381, 'Juggernaut', 'Male', 'blue', 'Human', 'Red', 287, 'Marvel Comics', '-', 'neutral', 855);
INSERT INTO hero VALUES (382, 'Junkpile', 'Male', '-', 'Mutant', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (383, 'Justice', 'Male', 'hazel', 'Human', 'Brown', 178, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (384, 'Jyn Erso', 'Female', 'green', 'Human', 'Brown', -99, 'George Lucas', '-', 'good', -99);
INSERT INTO hero VALUES (385, 'K-2SO', 'Male', 'white', 'Android', 'No Hair', 213, 'George Lucas', 'gray', 'good', -99);
INSERT INTO hero VALUES (386, 'Kang', 'Male', 'brown', '-', 'Brown', 191, 'Marvel Comics', '-', 'bad', 104);
INSERT INTO hero VALUES (387, 'Karate Kid', 'Male', 'brown', 'Human', 'Brown', 173, 'DC Comics', '-', 'good', 72);
INSERT INTO hero VALUES (388, 'Kathryn Janeway', 'Female', '-', 'Human', '-', -99, 'Star Trek', '-', 'good', -99);
INSERT INTO hero VALUES (389, 'Katniss Everdeen', 'Female', '-', 'Human', '-', -99, NULL, '-', 'good', -99);
INSERT INTO hero VALUES (390, 'Kevin 11', 'Male', '-', 'Human', 'Black', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (391, 'Kick-Ass', 'Male', 'blue', 'Human', 'Blond', -99, 'Icon Comics', '-', 'good', -99);
INSERT INTO hero VALUES (392, 'Kid Flash', 'Male', 'green', 'Human', 'Red', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (393, 'Kid Flash II', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (394, 'Killer Croc', 'Male', 'red', 'Metahuman', 'No Hair', 244, 'DC Comics', 'green', 'bad', 356);
INSERT INTO hero VALUES (395, 'Killer Frost', 'Female', 'blue', 'Human', 'Blond', -99, 'DC Comics', 'blue', 'bad', -99);
INSERT INTO hero VALUES (396, 'Kilowog', 'Male', 'red', 'Bolovaxian', 'No Hair', 234, 'DC Comics', 'pink', 'good', 324);
INSERT INTO hero VALUES (397, 'King Kong', 'Male', 'yellow', 'Animal', 'Black', 30.5, NULL, '-', 'good', NULL);
INSERT INTO hero VALUES (398, 'King Shark', 'Male', 'black', 'Animal', 'No Hair', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (399, 'Kingpin', 'Male', 'blue', 'Human', 'No Hair', 201, 'Marvel Comics', '-', 'bad', 203);
INSERT INTO hero VALUES (400, 'Klaw', 'Male', 'red', 'Human', 'No Hair', 188, 'Marvel Comics', 'red', 'bad', 97);
INSERT INTO hero VALUES (401, 'Kool-Aid Man', 'Male', 'black', '-', 'No Hair', -99, NULL, 'red', 'good', -99);
INSERT INTO hero VALUES (402, 'Kraven II', 'Male', 'brown', 'Human', 'Black', 191, 'Marvel Comics', '-', 'bad', 99);
INSERT INTO hero VALUES (403, 'Kraven the Hunter', 'Male', 'brown', 'Human', 'Black', 183, 'Marvel Comics', '-', 'bad', 106);
INSERT INTO hero VALUES (404, 'Krypto', 'Male', 'blue', 'Kryptonian', 'White', 64, 'DC Comics', '-', 'good', 18);
INSERT INTO hero VALUES (405, 'Kyle Rayner', 'Male', 'green', 'Human', 'Black', 180, 'DC Comics', '-', 'good', 79);
INSERT INTO hero VALUES (406, 'Kylo Ren', 'Male', '-', 'Human', '-', -99, 'George Lucas', '-', 'bad', -99);
INSERT INTO hero VALUES (407, 'Lady Bullseye', 'Female', '-', '-', 'Black', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (408, 'Lady Deathstrike', 'Female', 'brown', 'Cyborg', 'Black', 175, 'Marvel Comics', '-', 'bad', 58);
INSERT INTO hero VALUES (409, 'Leader', 'Male', 'green', '-', 'No Hair', 178, 'Marvel Comics', '-', 'bad', 63);
INSERT INTO hero VALUES (410, 'Leech', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (411, 'Legion', 'Male', 'green / blue', 'Mutant', 'Black', 175, 'Marvel Comics', '-', 'good', 59);
INSERT INTO hero VALUES (412, 'Leonardo', 'Male', 'blue', 'Mutant', 'No Hair', -99, 'IDW Publishing', 'green', 'good', -99);
INSERT INTO hero VALUES (413, 'Lex Luthor', 'Male', 'green', 'Human', 'No Hair', 188, 'DC Comics', '-', 'bad', 95);
INSERT INTO hero VALUES (414, 'Light Lass', 'Female', 'blue', '-', 'Red', 165, 'DC Comics', '-', 'good', 54);
INSERT INTO hero VALUES (415, 'Lightning Lad', 'Male', 'blue', '-', 'Red', 155, 'DC Comics', '-', 'good', 65);
INSERT INTO hero VALUES (416, 'Lightning Lord', 'Male', 'blue', '-', 'Red', 191, 'DC Comics', '-', 'bad', 95);
INSERT INTO hero VALUES (417, 'Living Brain', '-', 'yellow', '-', '-', 198, 'Marvel Comics', '-', 'bad', 360);
INSERT INTO hero VALUES (418, 'Living Tribunal', '-', 'blue', 'Cosmic Entity', 'No Hair', -99, 'Marvel Comics', 'gold', 'neutral', -99);
INSERT INTO hero VALUES (419, 'Liz Sherman', 'Female', '-', '-', '-', -99, 'Dark Horse Comics', '-', 'good', -99);
INSERT INTO hero VALUES (420, 'Lizard', 'Male', 'red', 'Human', 'No Hair', 203, 'Marvel Comics', '-', 'bad', 230);
INSERT INTO hero VALUES (421, 'Lobo', 'Male', 'red', 'Czarnian', 'Black', 229, 'DC Comics', 'blue-white', 'neutral', 288);
INSERT INTO hero VALUES (422, 'Loki', 'Male', 'green', 'Asgardian', 'Black', 193, 'Marvel Comics', '-', 'bad', 236);
INSERT INTO hero VALUES (423, 'Longshot', 'Male', 'blue', 'Human', 'Blond', 188, 'Marvel Comics', '-', 'good', 36);
INSERT INTO hero VALUES (424, 'Luke Cage', 'Male', 'brown', 'Human', 'Black', 198, 'Marvel Comics', '-', 'good', 191);
INSERT INTO hero VALUES (425, 'Luke Campbell', 'Male', '-', '-', '-', -99, 'NBC - Heroes', '-', 'bad', -99);
INSERT INTO hero VALUES (426, 'Luke Skywalker', 'Male', 'blue', 'Human', 'Blond', 168, 'George Lucas', '-', 'good', 77);
INSERT INTO hero VALUES (427, 'Luna', 'Female', '-', 'Human', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (428, 'Lyja', 'Female', 'green', '-', 'Green', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (429, 'Mach-IV', 'Male', 'brown', '-', 'Brown', 180, 'Marvel Comics', '-', 'bad', 79);
INSERT INTO hero VALUES (430, 'Machine Man', '-', 'red', '-', 'Black', 183, 'Marvel Comics', '-', 'good', 383);
INSERT INTO hero VALUES (431, 'Magneto', 'Male', 'grey', 'Mutant', 'White', 188, 'Marvel Comics', '-', 'bad', 86);
INSERT INTO hero VALUES (432, 'Magog', 'Male', 'blue', '-', 'Blond', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (433, 'Magus', 'Male', 'black', '-', '-', 183, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (434, 'Man of Miracles', '-', 'blue', 'God / Eternal', 'Silver', -99, 'Image Comics', '-', '-', -99);
INSERT INTO hero VALUES (435, 'Man-Bat', 'Male', 'brown', 'Human', 'Brown', -99, 'DC Comics', '-', 'neutral', -99);
INSERT INTO hero VALUES (436, 'Man-Thing', 'Male', 'red', '-', 'No Hair', 213, 'Marvel Comics', 'green', 'good', 225);
INSERT INTO hero VALUES (437, 'Man-Wolf', 'Male', 'brown', '-', 'Auburn', 188, 'Marvel Comics', '-', 'good', 90);
INSERT INTO hero VALUES (438, 'Mandarin', 'Male', 'blue', 'Human', 'White', 188, 'Marvel Comics', '-', 'bad', 97);
INSERT INTO hero VALUES (439, 'Mantis', 'Female', 'green', 'Human-Kree', 'Black', 168, 'Marvel Comics', 'green', 'good', 52);
INSERT INTO hero VALUES (440, 'Martian Manhunter', 'Male', 'red', 'Martian', 'No Hair', 201, 'DC Comics', 'green', 'good', 135);
INSERT INTO hero VALUES (441, 'Marvel Girl', 'Female', 'green', '-', 'Red', 170, 'Marvel Comics', '-', 'good', 56);
INSERT INTO hero VALUES (442, 'Master Brood', 'Male', 'blue', '-', 'Black', 183, 'Team Epic TV', '-', 'good', 81);
INSERT INTO hero VALUES (443, 'Master Chief', 'Male', 'brown', 'Human / Altered', 'Brown', 213, 'Microsoft', '-', 'good', -99);
INSERT INTO hero VALUES (444, 'Match', 'Male', 'black', '-', 'Black', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (445, 'Matt Parkman', 'Male', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (446, 'Maverick', 'Male', 'blue', '-', 'Black', 193, 'Marvel Comics', '-', 'good', 110);
INSERT INTO hero VALUES (447, 'Maxima', 'Female', 'brown', '-', 'Red', 180, 'DC Comics', '-', 'bad', 72);
INSERT INTO hero VALUES (448, 'Maya Herrera', 'Female', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (449, 'Medusa', 'Female', 'green', 'Inhuman', 'Red', 180, 'Marvel Comics', '-', 'good', 59);
INSERT INTO hero VALUES (450, 'Meltdown', 'Female', 'blue', '-', 'Blond', 165, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (451, 'Mephisto', 'Male', 'white', '-', 'Black', 198, 'Marvel Comics', '-', 'bad', 140);
INSERT INTO hero VALUES (452, 'Mera', 'Female', 'blue', 'Atlantean', 'Red', 175, 'DC Comics', '-', 'good', 72);
INSERT INTO hero VALUES (453, 'Metallo', 'Male', 'green', 'Android', 'Brown', 196, 'DC Comics', '-', 'bad', 90);
INSERT INTO hero VALUES (454, 'Metamorpho', 'Male', 'black', '-', 'No Hair', 185, 'DC Comics', '-', 'good', 90);
INSERT INTO hero VALUES (455, 'Meteorite', 'Female', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (456, 'Metron', 'Male', 'blue', '-', 'Black', 185, 'DC Comics', '-', 'good', 86);
INSERT INTO hero VALUES (457, 'Micah Sanders', 'Male', 'brown', '-', 'Black', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (458, 'Michelangelo', 'Male', 'blue', 'Mutant', '-', -99, 'IDW Publishing', 'green', 'good', -99);
INSERT INTO hero VALUES (459, 'Micro Lad', 'Male', 'grey', '-', 'Brown', 183, 'DC Comics', '-', 'good', 77);
INSERT INTO hero VALUES (460, 'Mimic', 'Male', 'brown', '-', 'Brown', 188, 'Marvel Comics', '-', 'good', 101);
INSERT INTO hero VALUES (461, 'Minna Murray', 'Female', '-', '-', '-', -99, 'Wildstorm', '-', 'good', -99);
INSERT INTO hero VALUES (462, 'Misfit', 'Female', 'blue', '-', 'Red', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (463, 'Miss Martian', 'Female', 'red', '-', 'Red', 178, 'DC Comics', '-', 'good', 61);
INSERT INTO hero VALUES (464, 'Mister Fantastic', 'Male', 'brown', 'Human / Radiation', 'Brown', 185, 'Marvel Comics', '-', 'good', 81);
INSERT INTO hero VALUES (465, 'Mister Freeze', 'Male', '-', 'Human', '-', 183, 'DC Comics', '-', 'bad', 86);
INSERT INTO hero VALUES (466, 'Mister Knife', 'Male', 'blue', 'Spartoi', 'Brown', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (467, 'Mister Mxyzptlk', 'Male', '-', 'God / Eternal', '-', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (468, 'Mister Sinister', 'Male', 'red', 'Human / Altered', 'Black', 196, 'Marvel Comics', '-', 'bad', 128);
INSERT INTO hero VALUES (469, 'Mister Zsasz', 'Male', 'blue', 'Human', 'Blond', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (470, 'Mockingbird', 'Female', 'blue', 'Human', 'Blond', 175, 'Marvel Comics', '-', 'good', 61);
INSERT INTO hero VALUES (471, 'MODOK', 'Male', 'white', 'Cyborg', 'Brownn', 366, 'Marvel Comics', '-', 'bad', 338);
INSERT INTO hero VALUES (472, 'Mogo', 'Male', '-', 'Planet', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (473, 'Mohinder Suresh', 'Male', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (474, 'Moloch', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (475, 'Molten Man', 'Male', 'gold', '-', 'Gold', 196, 'Marvel Comics', '-', 'bad', 248);
INSERT INTO hero VALUES (476, 'Monarch', 'Male', 'blue', '-', 'White', 193, 'DC Comics', '-', 'good', 90);
INSERT INTO hero VALUES (477, 'Monica Dawson', 'Female', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (478, 'Moon Knight', 'Male', 'brown', 'Human', 'Brown', 188, 'Marvel Comics', '-', 'good', 101);
INSERT INTO hero VALUES (479, 'Moonstone', 'Female', 'blue', '-', 'Blond', 180, 'Marvel Comics', '-', 'bad', 59);
INSERT INTO hero VALUES (480, 'Morlun', 'Male', 'white / red', '-', 'Black', 188, 'Marvel Comics', '-', 'bad', 79);
INSERT INTO hero VALUES (481, 'Morph', 'Male', 'white', '-', 'No Hair', 178, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (482, 'Moses Magnum', 'Male', 'brown', '-', 'Black', 175, 'Marvel Comics', '-', 'bad', 72);
INSERT INTO hero VALUES (483, 'Mr Immortal', 'Male', 'blue', 'Mutant', 'Blond', 188, 'Marvel Comics', '-', 'good', 70);
INSERT INTO hero VALUES (484, 'Mr Incredible', 'Male', 'blue', 'Human', 'Blond', 201, 'Dark Horse Comics', '-', 'good', 158);
INSERT INTO hero VALUES (485, 'Ms Marvel II', 'Female', 'blue', '-', 'Red', 173, 'Marvel Comics', '-', 'good', 61);
INSERT INTO hero VALUES (486, 'Multiple Man', 'Male', 'blue', '-', 'Brown', 180, 'Marvel Comics', '-', 'good', 70);
INSERT INTO hero VALUES (487, 'Mysterio', 'Male', 'brown', 'Human', 'No Hair', 180, 'Marvel Comics', '-', 'bad', 79);
INSERT INTO hero VALUES (488, 'Mystique', 'Female', 'yellow (without irises)', 'Mutant', 'Red / Orange', 178, 'Marvel Comics', 'blue', 'bad', 54);
INSERT INTO hero VALUES (489, 'Namor', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (490, 'Namor', 'Male', 'grey', 'Atlantean', 'Black', 188, 'Marvel Comics', '-', 'good', 125);
INSERT INTO hero VALUES (491, 'Namora', 'Female', 'blue', '-', 'Blond', 180, 'Marvel Comics', '-', 'good', 85);
INSERT INTO hero VALUES (492, 'Namorita', 'Female', 'blue', '-', 'Blond', 168, 'Marvel Comics', '-', 'good', 101);
INSERT INTO hero VALUES (493, 'Naruto Uzumaki', 'Male', '-', 'Human', '-', 168, 'Shueisha', '-', 'good', 54);
INSERT INTO hero VALUES (494, 'Nathan Petrelli', 'Male', 'brown', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (495, 'Nebula', 'Female', 'blue', 'Luphomoid', 'No Hair', 185, 'Marvel Comics', 'blue', 'bad', 83);
INSERT INTO hero VALUES (496, 'Negasonic Teenage Warhead', 'Female', 'black', 'Mutant', 'Black', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (497, 'Nick Fury', 'Male', 'brown', 'Human', 'Brown / White', 185, 'Marvel Comics', '-', 'good', 99);
INSERT INTO hero VALUES (498, 'Nightcrawler', 'Male', 'yellow', '-', 'Indigo', 175, 'Marvel Comics', '-', 'good', 88);
INSERT INTO hero VALUES (499, 'Nightwing', 'Male', 'blue', 'Human', 'Black', 178, 'DC Comics', '-', 'good', 79);
INSERT INTO hero VALUES (500, 'Niki Sanders', 'Female', 'blue', '-', 'Blond', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (501, 'Nina Theroux', 'Female', '-', 'Alpha', '-', -99, 'SyFy', '-', 'good', -99);
INSERT INTO hero VALUES (502, 'Nite Owl II', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (503, 'Northstar', 'Male', 'blue', '-', 'Black', 180, 'Marvel Comics', '-', 'good', 83);
INSERT INTO hero VALUES (504, 'Nova', 'Male', 'brown', 'Human', 'Brown', 185, 'Marvel Comics', '-', 'good', 86);
INSERT INTO hero VALUES (505, 'Nova', 'Female', 'white', 'Human / Cosmic', 'Red', 163, 'Marvel Comics', 'gold', 'good', 59);
INSERT INTO hero VALUES (506, 'Odin', 'Male', 'blue', 'God / Eternal', 'White', 206, 'Marvel Comics', '-', 'good', 293);
INSERT INTO hero VALUES (507, 'Offspring', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (508, 'Omega Red', 'Male', 'red', '-', 'Blond', 211, 'Marvel Comics', '-', 'bad', 191);
INSERT INTO hero VALUES (509, 'Omniscient', 'Male', 'brown', '-', 'Black', 180, 'Team Epic TV', '-', 'good', 65);
INSERT INTO hero VALUES (510, 'One Punch Man', 'Male', '-', 'Human', 'No Hair', 175, 'Shueisha', '-', 'good', 69);
INSERT INTO hero VALUES (511, 'One-Above-All', '-', '-', 'Cosmic Entity', '-', -99, 'Marvel Comics', '-', 'neutral', -99);
INSERT INTO hero VALUES (512, 'Onslaught', 'Male', 'red', 'Mutant', 'No Hair', 305, 'Marvel Comics', '-', 'bad', 405);
INSERT INTO hero VALUES (513, 'Oracle', 'Female', 'blue', 'Human', 'Red', 178, 'DC Comics', '-', 'good', 59);
INSERT INTO hero VALUES (514, 'Osiris', 'Male', 'brown', '-', 'Brown', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (515, 'Overtkill', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (516, 'Ozymandias', 'Male', 'blue', 'Human', 'Blond', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (517, 'Parademon', '-', '-', 'Parademon', '-', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (518, 'Paul Blart', 'Male', '-', 'Human', '-', 170, 'Sony Pictures', '-', 'good', 117);
INSERT INTO hero VALUES (519, 'Penance', '-', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (520, 'Penance I', 'Female', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (521, 'Penance II', 'Male', 'blue', '-', 'Blond', 183, 'Marvel Comics', '-', 'good', 89);
INSERT INTO hero VALUES (522, 'Penguin', 'Male', 'blue', 'Human', 'Black', 157, 'DC Comics', '-', 'bad', 79);
INSERT INTO hero VALUES (523, 'Peter Petrelli', 'Male', '-', '-', '-', -99, 'NBC - Heroes', '-', 'good', -99);
INSERT INTO hero VALUES (524, 'Phantom', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (525, 'Phantom Girl', 'Female', 'blue', '-', 'Black', 168, 'DC Comics', '-', 'good', 54);
INSERT INTO hero VALUES (526, 'Phoenix', 'Female', 'green', 'Mutant', 'Red', 168, 'Marvel Comics', '-', 'good', 52);
INSERT INTO hero VALUES (527, 'Plantman', 'Male', 'green', 'Mutant', 'Grey', 183, 'Marvel Comics', '-', 'bad', 87);
INSERT INTO hero VALUES (528, 'Plastic Lad', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (529, 'Plastic Man', 'Male', 'blue', 'Human', 'Black', 185, 'DC Comics', '-', 'good', 80);
INSERT INTO hero VALUES (530, 'Plastique', 'Female', 'blue', '-', 'Red', 168, 'DC Comics', '-', 'bad', 55);
INSERT INTO hero VALUES (531, 'Poison Ivy', 'Female', 'green', 'Human', 'Red', 168, 'DC Comics', 'green', 'bad', 50);
INSERT INTO hero VALUES (532, 'Polaris', 'Female', 'green', 'Mutant', 'Green', 170, 'Marvel Comics', '-', 'good', 52);
INSERT INTO hero VALUES (533, 'Power Girl', 'Female', 'blue', 'Kryptonian', 'blond', 180, 'DC Comics', '-', 'good', 81);
INSERT INTO hero VALUES (534, 'Power Man', 'Male', '-', 'Mutant', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (535, 'Predator', 'Male', '-', 'Yautja', '-', 213, 'Dark Horse Comics', '-', 'bad', 234);
INSERT INTO hero VALUES (536, 'Professor X', 'Male', 'blue', 'Mutant', 'No Hair', 183, 'Marvel Comics', '-', 'good', 86);
INSERT INTO hero VALUES (537, 'Professor Zoom', 'Male', 'blue', 'Human', 'Strawberry Blond', 180, 'DC Comics', '-', 'bad', 81);
INSERT INTO hero VALUES (538, 'Proto-Goblin', 'Male', 'green', '-', 'Blond', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (539, 'Psylocke', 'Female', 'blue', 'Mutant', 'Purple', 180, 'Marvel Comics', '-', 'good', 70);
INSERT INTO hero VALUES (540, 'Punisher', 'Male', 'blue', 'Human', 'Black', 183, 'Marvel Comics', '-', 'good', 90);
INSERT INTO hero VALUES (541, 'Purple Man', 'Male', 'purple', 'Human', 'Purple', 180, 'Marvel Comics', 'purple', 'bad', 74);
INSERT INTO hero VALUES (542, 'Pyro', 'Male', 'blue', '-', 'Blond', 178, 'Marvel Comics', '-', 'bad', 68);
INSERT INTO hero VALUES (543, 'Q', 'Male', '-', 'God / Eternal', '-', -99, 'Star Trek', '-', '-', -99);
INSERT INTO hero VALUES (544, 'Quantum', 'Male', '-', '-', '-', -99, 'HarperCollins', '-', 'good', -99);
INSERT INTO hero VALUES (545, 'Question', 'Male', 'blue', 'Human', 'Blond', 188, 'DC Comics', '-', 'good', 83);
INSERT INTO hero VALUES (546, 'Quicksilver', 'Male', 'blue', 'Mutant', 'Silver', 183, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (547, 'Quill', 'Male', 'brown', '-', 'Brown', 163, 'Marvel Comics', '-', 'good', 56);
INSERT INTO hero VALUES (548, 'Ra''s Al Ghul', 'Male', 'green', 'Human', 'Grey', 193, 'DC Comics', '-', 'bad', 97);
INSERT INTO hero VALUES (549, 'Rachel Pirzad', 'Female', '-', 'Alpha', '-', -99, 'SyFy', '-', 'good', -99);
INSERT INTO hero VALUES (550, 'Rambo', 'Male', 'brown', 'Human', 'Black', 178, NULL, '-', 'good', 83);
INSERT INTO hero VALUES (551, 'Raphael', 'Male', '-', 'Mutant', 'No Hair', -99, 'IDW Publishing', 'green', 'good', -99);
INSERT INTO hero VALUES (552, 'Raven', 'Female', 'indigo', 'Human', 'Black', 165, 'DC Comics', '-', 'neutral', 50);
INSERT INTO hero VALUES (553, 'Ray', 'Male', 'green', 'Human', 'Red', 178, 'DC Comics', '-', 'good', 70);
INSERT INTO hero VALUES (554, 'Razor-Fist II', 'Male', 'blue', '-', 'No Hair', 191, 'Marvel Comics', '-', 'bad', 117);
INSERT INTO hero VALUES (555, 'Red Arrow', 'Male', 'green', 'Human', 'Red', 180, 'DC Comics', '-', 'good', 83);
INSERT INTO hero VALUES (556, 'Red Hood', 'Male', 'blue', 'Human', 'Black', 183, 'DC Comics', '-', 'neutral', 81);
INSERT INTO hero VALUES (557, 'Red Hulk', 'Male', 'yellow', 'Human / Radiation', 'Black', 213, 'Marvel Comics', 'red', 'neutral', 630);
INSERT INTO hero VALUES (558, 'Red Mist', 'Male', '-', '-', '-', -99, 'Icon Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (559, 'Red Robin', 'Male', 'blue', 'Human', 'Black', 165, 'DC Comics', '-', 'good', 56);
INSERT INTO hero VALUES (560, 'Red Skull', 'Male', 'blue', '-', 'No Hair', 188, 'Marvel Comics', '-', 'bad', 108);
INSERT INTO hero VALUES (561, 'Red Tornado', 'Male', 'green', 'Android', 'No Hair', 185, 'DC Comics', '-', 'good', 146);
INSERT INTO hero VALUES (562, 'Redeemer II', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (563, 'Redeemer III', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (564, 'Renata Soliz', 'Female', '-', '-', '-', -99, 'HarperCollins', '-', 'good', -99);
INSERT INTO hero VALUES (565, 'Rey', 'Female', 'hazel', 'Human', 'Brown', 297, 'George Lucas', '-', 'good', -99);
INSERT INTO hero VALUES (566, 'Rhino', 'Male', 'brown', 'Human / Radiation', 'Brown', 196, 'Marvel Comics', '-', 'bad', 320);
INSERT INTO hero VALUES (567, 'Rick Flag', 'Male', 'blue', '-', 'Brown', 185, 'DC Comics', '-', 'bad', 85);
INSERT INTO hero VALUES (568, 'Riddler', 'Male', '-', '-', '-', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (569, 'Rip Hunter', 'Male', 'blue', 'Human', 'Blond', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (570, 'Ripcord', 'Female', 'green', '-', 'Black', 180, 'Marvel Comics', '-', 'good', 72);
INSERT INTO hero VALUES (571, 'Robin', 'Male', 'blue', 'Human', 'Black', 178, 'DC Comics', '-', 'good', 79);
INSERT INTO hero VALUES (572, 'Robin II', 'Male', 'blue', 'Human', 'Red', 183, 'DC Comics', '-', 'good', 101);
INSERT INTO hero VALUES (573, 'Robin III', 'Male', 'blue', 'Human', 'Black', 165, 'DC Comics', '-', 'good', 56);
INSERT INTO hero VALUES (574, 'Robin V', 'Male', 'blue', 'Human', 'Black', 137, 'DC Comics', '-', 'good', 38);
INSERT INTO hero VALUES (575, 'Robin VI', 'Female', 'green', 'Human', 'Red', -99, 'DC Comics', '-', 'neutral', -99);
INSERT INTO hero VALUES (576, 'Rocket Raccoon', 'Male', 'brown', 'Animal', 'Brown', 122, 'Marvel Comics', '-', 'good', 25);
INSERT INTO hero VALUES (577, 'Rogue', 'Female', 'green', '-', 'Brown / White', 173, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (578, 'Ronin', 'Male', 'blue', 'Human', 'Blond', 191, 'Marvel Comics', '-', 'good', 104);
INSERT INTO hero VALUES (579, 'Rorschach', 'Male', 'blue', 'Human', 'Red', 168, 'DC Comics', '-', 'good', 63);
INSERT INTO hero VALUES (580, 'Sabretooth', 'Male', 'amber', 'Mutant', 'Blond', 198, 'Marvel Comics', '-', 'bad', 171);
INSERT INTO hero VALUES (581, 'Sage', 'Female', 'blue', '-', 'Black', 170, 'Marvel Comics', '-', 'good', 61);
INSERT INTO hero VALUES (582, 'Sandman', 'Male', 'brown', 'Human', 'Brown', 185, 'Marvel Comics', '-', 'neutral', 203);
INSERT INTO hero VALUES (583, 'Sasquatch', 'Male', 'red', '-', 'Orange', 305, 'Marvel Comics', '-', 'good', 900);
INSERT INTO hero VALUES (584, 'Sauron', 'Male', '-', 'Maiar', '-', 279, 'J. R. R. Tolkien', '-', 'bad', -99);
INSERT INTO hero VALUES (585, 'Savage Dragon', 'Male', '-', '-', '-', -99, 'Image Comics', '-', 'good', -99);
INSERT INTO hero VALUES (586, 'Scarecrow', 'Male', 'blue', 'Human', 'Brown', 183, 'DC Comics', '-', 'bad', 63);
INSERT INTO hero VALUES (587, 'Scarlet Spider', 'Male', 'blue', 'Human', 'Blond', 178, 'Marvel Comics', '-', 'good', 74);
INSERT INTO hero VALUES (588, 'Scarlet Spider II', 'Male', 'brown', 'Clone', 'Brown', 193, 'Marvel Comics', '-', 'good', 113);
INSERT INTO hero VALUES (589, 'Scarlet Witch', 'Female', 'blue', 'Mutant', 'Brown', 170, 'Marvel Comics', '-', 'bad', 59);
INSERT INTO hero VALUES (590, 'Scorpia', 'Female', 'green', '-', 'Red', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (591, 'Scorpion', 'Male', 'brown', 'Human', 'Brown', 211, 'Marvel Comics', '-', 'bad', 310);
INSERT INTO hero VALUES (747, 'test2', 'test', 'test', 'test', 'test', 10, 'test', 'test', 'test', 10);
INSERT INTO hero VALUES (592, 'Sebastian Shaw', 'Male', '-', 'Mutant', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (593, 'Sentry', 'Male', 'blue', 'Mutant', 'Blond', 188, 'Marvel Comics', '-', 'neutral', 87);
INSERT INTO hero VALUES (594, 'Shadow King', '-', 'red', '-', '-', 185, 'Marvel Comics', '-', 'good', 149);
INSERT INTO hero VALUES (595, 'Shadow Lass', 'Female', 'black', 'Talokite', 'Black', 173, 'DC Comics', 'blue', 'good', 54);
INSERT INTO hero VALUES (596, 'Shadowcat', 'Female', 'hazel', 'Mutant', 'Brown', 168, 'Marvel Comics', '-', 'good', 50);
INSERT INTO hero VALUES (597, 'Shang-Chi', 'Male', 'brown', 'Human', 'Black', 178, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (598, 'Shatterstar', 'Male', 'brown', '-', 'Red', 191, 'Marvel Comics', '-', 'good', 88);
INSERT INTO hero VALUES (599, 'She-Hulk', 'Female', 'green', 'Human', 'Green', 201, 'Marvel Comics', '-', 'good', 315);
INSERT INTO hero VALUES (600, 'She-Thing', 'Female', 'blue', 'Human / Radiation', 'No Hair', 183, 'Marvel Comics', '-', 'good', 153);
INSERT INTO hero VALUES (601, 'Shocker', 'Male', 'brown', 'Human', 'Brown', 175, 'Marvel Comics', '-', 'bad', 79);
INSERT INTO hero VALUES (602, 'Shriek', 'Female', 'yellow / blue', '-', 'Black', 173, 'Marvel Comics', '-', 'good', 52);
INSERT INTO hero VALUES (603, 'Shrinking Violet', 'Female', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (604, 'Sif', 'Female', 'blue', 'Asgardian', 'Black', 188, 'Marvel Comics', '-', 'good', 191);
INSERT INTO hero VALUES (605, 'Silk', 'Female', 'brown', 'Human', 'Black', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (606, 'Silk Spectre', 'Female', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (607, 'Silk Spectre II', 'Female', '-', '-', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (608, 'Silver Surfer', 'Male', 'white', 'Alien', 'No Hair', 193, 'Marvel Comics', 'silver', 'good', 101);
INSERT INTO hero VALUES (609, 'Silverclaw', 'Female', 'brown', '-', 'Black', 157, 'Marvel Comics', '-', 'good', 50);
INSERT INTO hero VALUES (610, 'Simon Baz', 'Male', 'bown', 'Human', 'Black', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (611, 'Sinestro', 'Male', 'black', 'Korugaran', 'Black', 201, 'DC Comics', 'red', 'neutral', 92);
INSERT INTO hero VALUES (612, 'Siren', 'Female', 'blue', 'Atlantean', 'Purple', 175, 'DC Comics', '-', 'bad', 72);
INSERT INTO hero VALUES (613, 'Siren II', 'Female', 'black', '-', '-', -99, 'DC Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (614, 'Siryn', 'Female', 'blue', '-', 'Strawberry Blond', 168, 'Marvel Comics', '-', 'bad', 52);
INSERT INTO hero VALUES (615, 'Skaar', 'Male', 'green', '-', 'Black', 198, 'Marvel Comics', '-', 'good', 180);
INSERT INTO hero VALUES (616, 'Snake-Eyes', 'Male', '-', 'Animal', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (617, 'Snowbird', 'Female', 'white', '-', 'Blond', 178, 'Marvel Comics', '-', 'good', 49);
INSERT INTO hero VALUES (618, 'Sobek', 'Male', 'white', '-', 'No Hair', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (619, 'Solomon Grundy', 'Male', 'black', 'Zombie', 'White', 279, 'DC Comics', '-', 'bad', 437);
INSERT INTO hero VALUES (620, 'Songbird', 'Female', 'green', '-', 'Red / White', 165, 'Marvel Comics', '-', 'good', 65);
INSERT INTO hero VALUES (621, 'Space Ghost', 'Male', '-', 'Human', '-', 188, 'DC Comics', '-', 'good', 113);
INSERT INTO hero VALUES (622, 'Spawn', 'Male', 'brown', 'Demon', 'Black', 211, 'Image Comics', '-', 'good', 405);
INSERT INTO hero VALUES (623, 'Spectre', 'Male', 'white', 'God / Eternal', 'No Hair', -99, 'DC Comics', 'white', 'good', -99);
INSERT INTO hero VALUES (624, 'Speedball', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (625, 'Speedy', 'Male', '-', 'Human', '-', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (626, 'Speedy', 'Female', 'green', 'Human', 'Brown', -99, 'DC Comics', '-', 'good', -99);
INSERT INTO hero VALUES (627, 'Spider-Carnage', 'Male', '-', 'Symbiote', '-', -99, 'Marvel Comics', '-', 'bad', -99);
INSERT INTO hero VALUES (628, 'Spider-Girl', 'Female', 'blue', 'Human', 'Brown', 170, 'Marvel Comics', '-', 'good', 54);
INSERT INTO hero VALUES (629, 'Spider-Gwen', 'Female', 'blue', 'Human', 'Blond', 165, 'Marvel Comics', '-', 'good', 56);
INSERT INTO hero VALUES (630, 'Spider-Man', 'Male', 'hazel', 'Human', 'Brown', 178, 'Marvel Comics', '-', 'good', 74);
INSERT INTO hero VALUES (631, 'Spider-Man', '-', 'red', 'Human', 'Brown', 178, 'Marvel Comics', '-', 'good', 77);
INSERT INTO hero VALUES (632, 'Spider-Man', 'Male', 'brown', 'Human', 'Black', 157, 'Marvel Comics', '-', 'good', 56);
INSERT INTO hero VALUES (633, 'Spider-Woman', 'Female', 'green', 'Human', 'Black', 178, 'Marvel Comics', '-', 'good', 59);
INSERT INTO hero VALUES (634, 'Spider-Woman II', 'Female', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (635, 'Spider-Woman III', 'Female', 'brown', '-', 'Brown', 173, 'Marvel Comics', '-', 'good', 55);
INSERT INTO hero VALUES (636, 'Spider-Woman IV', 'Female', 'red', '-', 'White', 178, 'Marvel Comics', '-', 'bad', 58);
INSERT INTO hero VALUES (637, 'Spock', 'Male', 'brown', 'Human-Vulcan', 'Black', 185, 'Star Trek', '-', 'good', 81);
INSERT INTO hero VALUES (638, 'Spyke', 'Male', 'brown', 'Mutant', 'Blond', 183, 'Marvel Comics', '-', 'good', 83);
INSERT INTO hero VALUES (639, 'Stacy X', 'Female', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (640, 'Star-Lord', 'Male', 'blue', 'Human-Spartoi', 'Blond', 188, 'Marvel Comics', '-', 'good', 79);
INSERT INTO hero VALUES (641, 'Stardust', 'Male', '-', '-', '-', -99, 'Marvel Comics', '-', 'good', -99);
INSERT INTO hero VALUES (642, 'Starfire', 'Female', 'green', 'Tamaranean', 'Auburn', 193, 'DC Comics', 'orange', 'good', 71);
INSERT INTO hero VALUES (643, 'Stargirl', 'Female', 'blue', 'Human', 'Blond', 165, 'DC Comics', '-', 'good', 62);
INSERT INTO hero VALUES (644, 'Static', 'Male', 'brown', 'Mutant', 'Black', 170, 'DC Comics', '-', 'good', 63);
INSERT INTO hero VALUES (645, 'Steel', 'Male', 'brown', '-', 'No Hair', 201, 'DC Comics', '-', 'good', 131);
INSERT INTO hero VALUES (646, 'Stephanie Powell', 'Female', '-', '-', 'Blond', -99, 'ABC Studios', '-', 'good', -99);
INSERT INTO hero VALUES (647, 'Steppenwolf', 'Male', 'red', 'New God', 'Black', 183, 'DC Comics', 'white', 'bad', 91);
INSERT INTO hero VALUES (648, 'Storm', 'Female', 'blue', 'Mutant', 'White', 180, 'Marvel Comics', '-', 'good', 57);
INSERT INTO hero VALUES (649, 'Stormtrooper', 'Male', '-', 'Human', '-', 183, 'George Lucas', '-', 'bad', -99);
INSERT INTO hero VALUES (650, 'Sunspot', 'Male', 'brown', 'Mutant', 'black', 173, 'Marvel Comics', '-', 'good', 77);
INSERT INTO hero VALUES (651, 'Superboy', 'Male', 'blue', '-', 'Black', 170, 'DC Comics', '-', 'good', 68);